### ISSUE TITLE
Intermittent hanging with rake/rails commands

### ISSUE THREAD

**Issue by jemminger** [chanks/que#102]
Not sure how to debug this:

If I have Que running in async mode in development in Thin, occasionally other terminal tabs will hang if I run a rake command or start the rails console in another tab.

Usually I'll get output like `Finishing Que's current jobs before exiting...` and the process will never end.

Manually killing the ruby processes sometimes fixes the situation, other times it persists until I reboot.

Just now I quit Terminal with a hanging process, restarted Terminal, and tried to generate a migration.  I got a little more new output:

```
Last login: Thu Mar 26 17:49:46 on ttys003
mac-n-cheese:~ jemminger$ cd Rails/new_tsig/
mac-n-cheese:new_tsig jemminger$ rails g migration add_account_defaults
spring app    | new_tsig | started 4 secs ago | development mode(69177,0x107127000) malloc: *** error for object 0x7fab6d8b4000: double free
*** set a breakpoint in malloc_error_break to debug
mac-n-cheese:new_tsig jemminger$ rails g migration add_account_defaults
      invoke  active_record
      create    db/migrate/20150326223404_add_account_defaults.rb
Finishing Que's current jobs before exiting...
```

Any ideas?

**Comment by jemminger** [comment]
Adding to above:  after I CTRL+C the hung process above, I got a stacktrace:

```
^C/Users/jemminger/.rvm/gems/ruby-2.2.0@new_tsig/gems/que-0.9.2/lib/que/worker.rb:59:in `sleep': Interrupt
	from /Users/jemminger/.rvm/gems/ruby-2.2.0@new_tsig/gems/que-0.9.2/lib/que/worker.rb:59:in `wait'
	from /Users/jemminger/.rvm/gems/ruby-2.2.0@new_tsig/gems/que-0.9.2/lib/que/worker.rb:67:in `_sleeping?'
	from /Users/jemminger/.rvm/gems/ruby-2.2.0@new_tsig/gems/que-0.9.2/lib/que/worker.rb:48:in `stop'
	from /Users/jemminger/.rvm/gems/ruby-2.2.0@new_tsig/gems/que-0.9.2/lib/que/worker.rb:167:in `each'
	from /Users/jemminger/.rvm/gems/ruby-2.2.0@new_tsig/gems/que-0.9.2/lib/que/worker.rb:167:in `set_up_workers'
	from /Users/jemminger/.rvm/gems/ruby-2.2.0@new_tsig/gems/que-0.9.2/lib/que/worker.rb:141:in `worker_count='
	from /Users/jemminger/.rvm/gems/ruby-2.2.0@new_tsig/gems/que-0.9.2/lib/que.rb:101:in `block (2 levels) in singleton class'
	from /Users/jemminger/.rvm/gems/ruby-2.2.0@new_tsig/gems/que-0.9.2/lib/que/railtie.rb:21:in `block (3 levels) in <class:Railtie>'
	from /Users/jemminger/.rvm/gems/ruby-2.2.0@new_tsig/gems/spring-1.2.0/lib/spring/application.rb:156:in `fork'
	from /Users/jemminger/.rvm/gems/ruby-2.2.0@new_tsig/gems/spring-1.2.0/lib/spring/application.rb:156:in `serve'
	from /Users/jemminger/.rvm/gems/ruby-2.2.0@new_tsig/gems/spring-1.2.0/lib/spring/application.rb:131:in `block in run'
	from /Users/jemminger/.rvm/gems/ruby-2.2.0@new_tsig/gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
	from /Users/jemminger/.rvm/gems/ruby-2.2.0@new_tsig/gems/spring-1.2.0/lib/spring/application.rb:125:in `run'
	from /Users/jemminger/.rvm/gems/ruby-2.2.0@new_tsig/gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/jemminger/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/jemminger/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'

```

**Comment by chanks** [comment]
My guess is that async mode doesn't work well with Spring - are you able to
reproduce it without Spring running?

Also, just out of curiosity, what do you get from "SELECT * FROM
pg_stat_activity" when everything is hanging?

**Comment by jemminger** [comment]
Here's the sql output:

https://gist.github.com/jemminger/91f7a2bd19a13c329ddf

**Comment by chanks** [comment]
Nothing going on there. My apologies, I misread your initial post and thought something in PG was hanging when you tried to run the migration. Didn't realize it was starting up when the migration was being generated. It definitely shouldn't be doing that.

I'm starting to think the Railtie should never starting up the worker pool by default, it seems too dangerous (and it's certainly not tested well enough). And with Spring now being common in development, and autoloading not working well with multithreading... I think keeping that behavior around is asking for trouble.

**Comment by jemminger** [comment]
No worries.  I think for the meantime I'll just run development in `sync` mode.

**Comment by joevandyk** [comment]
I've noticed that sometimes when I send an INT to que (running in production), I get this:

```
recommender_que> Finishing Que's current jobs before exiting...
recommender_que> I, [2015-04-02T12:07:54.120693 #27263]  INFO -- : {"lib":"que","hostname":"job1","pid":27263,"thread":69886464784740,"event":"mode_change","value":"off"}
recommender_que> Que's jobs finished, exiting...
recommender_que> I, [2015-04-02T12:07:54.175460 #27263]  INFO -- : {"lib":"que","hostname":"job1","pid":27263,"thread":69886479008620,"event":"job_errored","error":{"class":"NoMethodError","message":"undefined method `rollback' for nil:NilClass"},"job":{"queue":"","priority":100,"run_at":"2015-04-02T19:05:30.056+00:00","job_id":8862654,"job_class":"ProcessEventJob","args":[{"id":14929283}],"error_count":0}}
```

And then it just hangs and doesn't respond to any signals. Not sure if related.

**Comment by joevandyk** [comment]
Tested it some more on one of these stuck processes, a `SIGINT` did nothing, but a `SIGTERM` did stop the application.

I'm using the 'rake que:work' task.

**Comment by joevandyk** [comment]
Hm, TERMs aren't always stopping it either. I wonder if this is related to https://github.com/rails/rails/issues/11118 ?

(again, the problem is when I sent an INT or TERM to a que process, it doesn't stop, it just hangs)

**Comment by joevandyk** [comment]
I'm getting this on Rails 4.2.0 btw.

**Comment by chanks** [comment]
The PR I've opened for a command-line interface that replaces the current ways of running jobs (#112) should solve the problem brought up in the original issue, and it also replaces the rake task.

Currently SIGINT and SIGTERM will both wait until the current jobs are finished working to shut down, and only a SIGKILL will end the process immediately (this is by design, see [here](https://github.com/chanks/que/blob/master/docs/shutting_down_safely.md) for an explanation why). @joevandyk are you sure that it's not a problem in your job's logic causing the hang?

**Comment by chanks** [comment]
I just pushed 0.11.0, which disables the worker pool from automatically starting, so the initial problem with the migrations/console shouldn't be an issue anymore.

The SIGINT/SIGTERM issue seems like something different, I'm not sure what's going on there, but since there's been no news in a few months and I don't have a reproduction, I'm going to close this. Feel free to reopen or start a new issue if that changes.

**Comment by zreisman** [comment]
This could happen if you are using 'rescue Exception' in your Rails app, which will also trap SIGINT/SIGTERM. SIGKILL (kill -9) is sent to the OS. If that's the case, change all instances of rescue Exception to StandardError or more specific. StandardError is the most broad error that should be rescued.
