### ISSUE TITLE
Hang (sleeping forever) after job enqueued (updated: should not start workers in master process in a forked server)

### ISSUE THREAD

**Issue by godfat** [chanks/que#111]
While I am digging into it, I would like to show you what I have now.
Since we're in a hurry, we might just do some workaround for now.

It hanged on this line:

``` ruby
Que.adapter.wake_worker_after_commit unless t
# the adapter is sequel adapter
```

The problem is located in worker's sleeping check:
Here it assumes whenever `@state == :sleeping`,
eventually `@thread.status == 'sleep'`:

``` ruby
    def _sleeping?
      if @state == :sleeping
        # There's a very small period of time between when the Worker marks
        # itself as sleeping and when it actually goes to sleep. Only report
        # true when we're certain the thread is sleeping.
        wait until @thread.status == 'sleep'
        true
      end
    end
```

But I got into a state that `@state == :sleeping` and `@thread.status == false`.
That means, this `@thread` is dead somehow, and the main thread
enqueuing the job would just sleep here forever.

My workaround would be simple, just don't wake the worker after enqueued.
Then everything works fine as far as I know.

I'll try to figure out why `@thread.status == false` in the mean time.

**Comment by godfat** [comment]
I think you might probably want to use ConditionVariable to wake up workers instead of having this state machine?

**Comment by chanks** [comment]
Yeah, the 1.0 branch already uses condition variables. Depending on what the issue is here I suppose I might consider switching to something similar in 0.x, since I plan on supporting it for a while after 1.0 is released.

Is it possible that your job raised an error that descended from Exception (rather than StandardError) and killed the worker thread? I'd expect the process to abort in that case, since we set abort_on_exception = true for worker threads, but I'm not sure how foolproof that option is. And if you can offer a self-contained reproduction I'd be happy to dig into it too.

**Comment by godfat** [comment]
> Yeah, the 1.0 branch already uses condition variables.
> [...]

Terrific! Would you recommend we just jump to 1.0 branch then? Is it stable enough now?

> Is it possible that your job raised an error that descended from Exception
> [...]

That's my first guess, too, but I didn't see any exception, and as you pointed out, the exception should bubble out with `abort_on_exception=true`. Also, according to the doc, if there's an exception aborting the thread, the status should be `nil` rather than `false`. False means the thread terminated normally. On the other hand, I never thought the worker thread is dead, because the job would get processed! And I have only one worker thread.

Simply skip `Que.wake!` after enqueued by always passing `:run_at => Time.now` works fine now. I am quite puzzled to be honest.

Since I could reliably reproduce this in our environment -- the call to enqueue always hangs if `Que.wake!` is called... I guess I could figure out something. Sorry that I cannot share the code nor to come up a self-contained reproduction (if I got one I'll let you know), but I'll show you how I configure Que.

* * *

And you know what? I found the root cause as I tried to list my environment. I've hit into this several times already, and I should have thought about this much earlier...

The problem is that, we're using a forked server (unicorn or yahns) along with `preload_app=true`, and you know that threads won't be forked over properly. Here the master process loads the application, setting up Que, starting workers (more on this later), and then forking the worker processes. Everything is copied over except *threads*. So the Que worker threads has never been started, while Que thinks that the worker is alive, which is false.

Some workers are indeed alive, which are in the master process. All workers under child processes are all dead from the beginning. This is why works are still being processed, by those workers in master process.

Since I found the issue, I successfully worked around it. But here's the thing I hope Que could improve -- Que should not automatically start the workers, or at least make it configurable.

Given current state, this is quite tricky as I have to put `gem 'que', :require => false` in the Gemfile to disallow Rails load Que automatically, because Que would also load `Que::Railtie` automatically which automatically start the workers by setting the mode to `:async`.

Now I tried to not load anything from Que, and only load Que after the processes are forked. But then I lose the advantage of setting `preload_app=true`.

Why we shouldn't start the workers upon loading the application:

* We don't want to start the workers while doing `rake assets:precompile`
* We don't want to start the workers while running `rake db:migrate` to setup tables for Que (well, I think we don't want to start the workers for other migrations as well)
* We don't want to start the workers for master process in a forked server.
* We might not want to run workers in the tests.

Instead of inferring what we might want to do, there are too many cases, I think we should allow the programmers to decide. However, it's fine to have `require 'que/auto'` to do automation though. I know it's convenient in some cases.

I propose to have `Que.start!` or `Que::Worker.start!`, and by default, workers should not be started. Setting `mode` and `worker_count` should not start the workers, either.

Does this make sense?

**Comment by chanks** [comment]
Yes, there have been a few issues already about the automatic startup not working correctly in various cases (#109 is the most recent), and it's on my TODO list to remove that functionality entirely in favor of a CLI, similar to what sidekiq (for example) has.

I wouldn't recommend jumping to 1.0 yet. I think its foundation is sound, but I'd like to support multiple job tables in it before shipping it and I'm not sure how that'll work yet.

**Comment by godfat** [comment]
Ok, great, thanks! Feel free to close this then. I would recommend to address this in high priority because people using forked server (even puma could fork now, as far as I know) along with preloading the application would definitely hit into this, and I think not many people would be going to figure out what's happening.

**Comment by chanks** [comment]
@godfat - just opened a PR (#112) with a command line interface to replace the autostarting logic. Try it out and let me know if you run into any problems?

Thanks!

**Comment by godfat** [comment]
Before I try it, I think this should work as long as it does not automatically start any workers. Personally I won't use the command line, running in the background is perfectly fine for me. I just need to confirm that:

It would only start the workers if `Que.mode = :async`, and the default isn't `:async`? So I could safely assume it would only start the workers if and only if `Que.mode = :async` is called. Even setting `Que.worker_count` would not start the worker before `Que.mode = :async`.

If so, then I think it should work fine. Thanks for the quick solution!

**Comment by chanks** [comment]
Thanks for your notes, I incorporated all of them, except for Que.stop, since I'm not sure what I want the API to look like yet for 1.0, and I don't really want to add some new methods just to possibly deprecate/remove them in a few months. I definitely agree that having both worker_count = 0 and mode = :off is confusing and unnecessary (mode = :off used to set worker_count = 0 and vice versa, but people found it troublesome and confusing).

Your understanding of how mode and worker_count work is correct. I think that a general solution for getting a background worker running in the same process is too painful, but I hope you find something that works for your app :)

**Comment by godfat** [comment]
Sure, as long as it's simple to copy around (just two lines), I am good with it. What about the default options then? It's quite surprising to see that it's not using what I've set while ./config/environment.rb was loaded for me.

As for running the workers in the same process, I am yet to sure if it's a good idea or not, but for small applications, I think it's good to save some managing cost. One process to rule them all :) And once the workers are starting to affect web servers, we could easily move them to a standalone process or a few worker processes. I think this is quite flexible. I used to run Sidekiq this way, too.

I am curious though, did you run into some troubles running them in the same process? Frankly I am quite happy when I figured out Que does support this. I have to [patch Sidekiq][] for doing this before. Not sure about now though, I didn't use Sidekiq for a while now.

[patch Sidekiq]: https://github.com/mperham/sidekiq/pull/664

**Comment by chanks** [comment]
I updated the default options like you suggested - is it not working for you? Glancing at the code, I don't see why it wouldn't.

I've never run into problems running the workers in the same process, but then, when I've used Que on a project it hasn't been with Rails or forking webservers :)

**Comment by godfat** [comment]
Umm? Did I miss something? Can you point me the commit you're referring to? Is it pushed to CLI branch? The last one I saw is: 5bc018986314943cbad53b92cab06136a9bfdf00

Haha, I see. Forking server is an easy one, just need to be aware of that. Fighting with Rails is a hard one, because there are so many libraries are trying to do things *smart* and some of them would just conflict. RR tries to pick a correct testing framework adapter is the toughest one... there are just too many possible combinations with different versions...

**Comment by chanks** [comment]
Ugh, sorry, wrote it with the other stuff on Saturday but had to run and forgot to commit it. So it's just been sitting here locally since then. Sorry about that!
