### ISSUE TITLE
Convert json column to jsonb to support args equality

### ISSUE THREAD

**Issue by hlascelles** [chanks/que#114]
Hi chanks,

We're using que to great effect, but would love to have the "unique job" functionality we see in resque _et al_. 

eg (pseudo code, where save enqueues a "send to elasticsearch" job keyed on id)
- start transaction
- edit customer and save!
- edit customer and save!
- edit customer and save!
- commit

At this point, we want to run just one "send to elasticsearch" job.

I started writing a plugin for Que that would check which prospectively enqueued jobs have the same args, but the json type doesn't support the equality operator. jsonb does.

Before I go about it, if I created a PR to move to jsonb, would you consider it?

H

**Comment by chanks** [comment]
If you're using sidekiq-middleware, I should point out that the unique flag doesn't prevent the same job from being enqueued with the same arguments more than once, it just prevents those jobs from running concurrently (see https://github.com/krasnoukhov/sidekiq-middleware/issues/24). I had the same misconception when I had to use Sidekiq on something.

Anyway, others have wanted to switch to JSONB for other reasons (ad-hoc querying on job arguments), but I think you probably have a better argument for it. Before puting any effort into it, though, have you considered/tried a solution in Ruby? Holding a thread-local array of the jobs that have been enqueued in the current transaction seems reasonable (though I haven't tried implementing it, so I may be wrong), and would be more performant than querying the DB before queuing each job. It also wouldn't require new indexes on the jobs table for fast operation.

**Comment by joevandyk** [comment]
You can convert json to text, like

where args::text = 'whatever'

**Comment by chanks** [comment]
I thought about that, but assumed that key ordering might change and throw
things off? If not, that'd be an even better solution.

**Comment by hlascelles** [comment]
Good thinking all, cheers...

We're using [Resque Solo](https://github.com/neighborland/resque_solo) which *does* prevent multiple enqueues, but *doesn't* prevent them running concurrently, so not the Sidekiq type. I can see virtue in both styles, but this is the one I'm gunning for.

Yes, key ordering will be a problem for the `::text` solution, but we (mostly) have "single id" arg jobs. So, good enough for us, though might not be good enough for the general public.

The thread local idea sounds good (more performant)... A couple of issues would be:

1) When would we write to the DB? Just before the commit of this transaction? If so, and another of the same job is created in an outer transaction later, should that one be added too? Should it depend on the semantics of the inner transaction?
2) Problems querying the queue during testing with [que-testing](https://github.com/statianzo/que-testing) (or indeed prod code).
````
ThisJob.enqueue
# Check for size of enqueued jobs.... zero! How strange...
````
I'm going to have a think. I suspect leaving the general case as normal (write to DB on enqueue) is less hazardous. Will put a PR together, and you can have a look.

**Comment by chanks** [comment]
For the Ruby solution, I think you'd write to the DB as normal, just check whether the job type and args you're persisting exist in a thread-local and transaction-specific array before doing the insert. I was also thinking of a solution that would prevent multiple queuings of the same job in the same transaction, not something that would prevent duplicates between different threads or processes. If you want that you'd going to need a DB-level solution.

I also think that, like the last person who wanted to convert the args column to JSONB, you might be able to get what you want out of an expression index on the args column cast to JSONB. That would probably let you do the fast lookup based on argument contents that you want without changing the column type for everyone, but I don't know enough about indexing JSONB to be sure.

I also think that this is probably an uncommon enough use case that it doesn't belong in Que core, but would make a good separate gem, so I'm going to close this. I'm not sure what changes you might need to Que core to support this (your solution might just be as simple as a module that can be included into the job classes that people want to enable this behavior for), but if you need something in particular (like a way to register callbacks or hooks or something) please open another issue.

**Comment by fameoflight** [comment]
@hlascelles were you able to find solution of uniquness problem? I am running into same issue would love use it as well. 

Also I have using que-scheduler for production thanks for that project as well.

**Comment by hlascelles** [comment]
Yes, we did indeed. We did it much the same way @chanks suggested. We have used it in production for many years, bug free.

I have just released as-is from our codebase as [que-unique](https://github.com/bambooengineering/que-unique).

Usage:

```ruby
# Add to Gemfile
gem 'que-unique'

# Add the `include` to your job
class SomeUniqueJob < Que::Job
 include Que::Unique
end
```

That's it. It should "just work". If you enqueue multiple jobs of the same args *in the same transaction* it will coalesce them into one.

Give it a go, and if it works out for you I'll add a PR to add it to the que documentation.

Glad you are using `que-scheduler`!

**Comment by fameoflight** [comment]
Looking at the code, it seems like it only work when enqueuing jobs in single thread, but not otherwise 

I was thinking of adding unique_key to que_job and just checking it,  example would be  

```ruby
SomeJob.enqueue(id, unique_key: “123”) 
```

Now if there is one job already in table with same unique key, 

```ruby
SomeJob.enqueue(id, unique_key: “123”)  #  Will be no op 
```

Your code did give me idea on how I can make it work.

**Comment by hlascelles** [comment]
OK, interesting. Maybe que-locks is what you need. This discussion probably needs a new issue. I will start one that will cover this topic: https://github.com/bambooengineering/que-unique/issues/1
