### ISSUE TITLE
Monitoring hook

### ISSUE THREAD

**Issue by wvengen** [chanks/que#119]
Is there a preferred way to implement global hooks for jobs? I'm trying to figure out introduce job statistics monitoring to Que (with [appsignal](https://github.com/appsignal/appsignal) in my case).

All that's needed is to have a wrapper around `run` for all jobs. I could chain `Que::Job._run`, but I'm not sure if I can count on this method to remain.

Any advice?

**Comment by chanks** [comment]
Probably a better option would be to define your own module with a `run` method that calls `super`, and then prepend it into `Que::Job`.

`_run` probably isn't going anywhere anytime soon, but that's not a guarantee.

**Comment by saturnflyer** [comment]
I'm using both Que and AppSignal too @wvengen. What did you end up doing?

**Comment by chanks** [comment]
I'm going to close this since it seems settled, but please feel free to reopen if there's more.

**Comment by wvengen** [comment]
Thanks, that's a great idea. Haven't finished anything, but will post here when I'm done.

**Comment by wvengen** [comment]
Settled on using `prepend`on `_run` with `Que::Job`, because I'd like to instrument all jobs without requiring a `prepend` line in jobs using this. And, of course, all jobs override `run` so that ends up at the top of the ancestor chain.

**Comment by wvengen** [comment]
@saturnflyer see this [feature/integration-que](https://github.com/q-m/appsignal/compare/master...q-m:feature/integration-que?expand=1) branch that I hope to merge into the appsignal gem. Please feel free to comment on the commit, if you see anything that could be improved.
