### ISSUE TITLE
Workers not starting automatically under `rails server`

### ISSUE THREAD

**Issue by CraigCottingham** [chanks/que#132]
I have queued up a number of jobs using ActiveJob, but my application isn't starting worker threads and processing the queue automatically. I have to run `rails console` separately, then enable workers with `Que.mode = :async`. Furthermore, it looks like the worker threads are in the console process, not the server process, because if I terminate the console process, jobs stop being run.

I tried setting the mode explicitly in my application's `application.rb` with `config.que.mode = :async`, but that generated an error to the effect that AR hadn't finished initializing the database connection when Que tried using it. (I don't have the error handy, but I should be able to recreate it easily enough if need be.)

Is there something else I need to do (or can do) to get the worker threads starting automatically in my server process?

**Comment by chanks** [comment]
What version are you on? I removed the automatic startup a couple versions
ago due to just this type of problem (workers starting up in the console or
rake tasks and generally being difficult to manage).

**Comment by CraigCottingham** [comment]
0.11.2. The README at https://github.com/chanks/que#usage still says

> Que.mode = :async - In this mode, a pool of background workers is spun up, each running in their own thread. This is the default when running bin/rails server.

**Comment by CraigCottingham** [comment]
BTW, I realize that integration with Rails/AJ is still up in the air (per issue #127). If there's anything I can do to help with the code and/or documentation (since I seem to be out here taking arrows anyway :-)), please let me know.

**Comment by chanks** [comment]
Ah, I'll fix the docs then. And there'll be a new project around Rails
integration at some point that I'm sure will need help, so don't fear :)

**Comment by chanks** [comment]
Fixed the README, thanks!
