### ISSUE TITLE
Should this sleep in bin/que match the wake interval?

### ISSUE THREAD

**Issue by tpitale** [chanks/que#133]
https://github.com/chanks/que/blob/master/bin/que#L79

Thoughts on having that match the wake interval setting?

**Comment by tpitale** [comment]
I'd be happy to send a PR :smile:

**Comment by chanks** [comment]
Nope, that's just to check every so often whether a signal has been sent to
stop the process. This isn't the first time it's come up, though, so maybe
it should be better commented :)

**Comment by tpitale** [comment]
To clarify, I realize it's not supposed to be the wake interval to be functional. Just wondering if there's any point for that sleep to be shorter than the wake interval. E.g., if my workers each sleep for 1 second or even 30 seconds, does the check need to be happening quite as often?

**Comment by joevandyk** [comment]
If the delay was 30 seconds, then it wuld take up to 30 seconds to quit the program when you sent it a SIGINT during deploys, which doesn't seem ideal.

**Comment by tpitale** [comment]
Isn't that what happens anyway if you have to wait for the worker threads to stop? If their wake interval is 30 seconds, you're going to be waiting that long.

**Comment by tpitale** [comment]
Regardless, I totally defer to your judgement, @chanks. Just thought I'd bring it up.

**Comment by tpitale** [comment]
Nevermind. Looking at the code again, it's clear the wrangler is the only thread that cares about the wake interval. And that appears to just be allowed to die at exit.

**Comment by chanks** [comment]
That's right. No problem! :)
