### ISSUE TITLE
Not seeing work done concurrently no matter the worker config

### ISSUE THREAD

**Issue by tpitale** [chanks/que#135]
I'm not certain, but I think because `Job.work` is a class method, and the jobs themselves are not inherently run in another thread, I think https://github.com/chanks/que/blob/master/lib/que/job.rb#L100 will block any other worker from working a job. Multiple workers can claim jobs, but they have to wait for `Job.work` to finish each one at a time …?

I could certainly be doing something wrong. Like, should I wrap my job `run` in a `Thread` myself?

**Comment by chanks** [comment]
Hmm, no, Job.work being a class method won't stop it from being called by
multiple threads simultaneously. Even if it were manipulating a shared
piece of data (like a class variable) Ruby wouldn't magically lock anything
for you, you'd just see weird errors. And the internal worker/pool logic
will take care of running jobs in different threads, you shouldn't need to
do it manually.

Not sure why offhand why you wouldn't see multiple jobs work concurrently.
A few ideas:

- is your worker count greater than one? And/or are you running multiple
job processes? I'm curious whether you're seeing one job work at a time in
a single process or across all of them.
- are you sure that there's multiple jobs available to run? Is it possible
that your code is only enqueuing one job at a time rather than many?
- if you make sure the process has plenty of time to run other jobs, like
by sleeping for a few seconds in your job's run action, do you see the same
behavior?

If you're able to put together a self-contained reproduction of the issue
I'm happy to look at it. In my experience, though, it's usually the act of
creating the reproduction that shows you that you did something wrong. At
least, that's how it usually goes when I report an issue in something I use
:)

**Comment by tpitale** [comment]
Just wanted to say thanks for your reply and work on this gem!

And now, answers to your questions:

* Been able to reproduce with 1 process and 2 workers.
* I've tried queuing a few different ways, but for testing I've queued a bunch of work ahead of time.
* The job I've created to test this does nothing but work and sleep.
* I've added additional logging to show the thread object id of the workers in the pool and there state. I can see the log for the first worker go from sleeping to working. Then the next wait interval passes before the wrangler thread wakes the second worker. That worker changes to the working state, but the job itself is not run.

I'd just like to point out that `Job` is a constant, shared between threads. I'm writing up a quick proof to see how Ruby behaves when calling methods like this, because I'm honestly not certain.

Also, I'm running this on MRI, so I don't expect it to be really parallel. My app's real jobs just do a lot of IO that should allow other worker threads to do something concurrently.

**Comment by tpitale** [comment]
Okay. Here's what I did, and you're right, that doesn't block:

```ruby
class Job
  def self.work
    10.times do |i|
      puts "Working in #{Thread.current.object_id}, loop #{i}"
      sleep 10
    end
  end
end

threads = 2.times.map do
  Thread.new do
    Job.work
  end
end

threads.each(&:join)
```

So, I'll have to dig more.

For the record, here's the test job I'm running:

```ruby
module Jobs
  class Sleepy < Que::Job
    @queue = [Rails.env, :default].join('.')

    def run
      10.times do |i|
        msg = "Working in process #{Process.pid}, thread: #{Thread.current.object_id}, loop: #{i}"
        Rails.logger.info msg
        sleep 2
      end
    end
  end
end
```

**Comment by tpitale** [comment]
```bash
bundle exec que -q "development.default" -w 2 ./config/environment.rb
```

And the logs this produces:

```
{"lib":"que","hostname":"aether.local","pid":83717,"thread":70272321708500,"event":"worker_count_change","value":"2"}
{"lib":"que","hostname":"aether.local","pid":83717,"thread":70272321708500,"event":"mode_change","value":"async"}
Working in process 83717, thread: 70272358132940, loop: 0
Working in process 83717, thread: 70272358132940, loop: 1
Working in process 83717, thread: 70272358132940, loop: 2
Working in process 83717, thread: 70272358132940, loop: 3
Working in process 83717, thread: 70272358132940, loop: 4
Working in process 83717, thread: 70272358132940, loop: 5
Working in process 83717, thread: 70272358132940, loop: 6
Working in process 83717, thread: 70272358132940, loop: 7
Working in process 83717, thread: 70272358132940, loop: 8
Working in process 83717, thread: 70272358132940, loop: 9
{"lib":"que","hostname":"aether.local","pid":83717,"thread":70272358132940,"event":"job_worked","job":{"queue":"development.default","priority":100,"run_at":"2015-11-26T23:23:22.615-05:00","job_id":26,"job_class":"Jobs::Sleepy","args":[],"error_count":0},"elapsed":20.0484}
Working in process 83717, thread: 70272358098660, loop: 0
Working in process 83717, thread: 70272358098660, loop: 1
Working in process 83717, thread: 70272358098660, loop: 2
Working in process 83717, thread: 70272358098660, loop: 3
Working in process 83717, thread: 70272358098660, loop: 4
Working in process 83717, thread: 70272358098660, loop: 5
Working in process 83717, thread: 70272358098660, loop: 6
Working in process 83717, thread: 70272358098660, loop: 7
Working in process 83717, thread: 70272358098660, loop: 8
Working in process 83717, thread: 70272358098660, loop: 9
{"lib":"que","hostname":"aether.local","pid":83717,"thread":70272358098660,"event":"job_worked","job":{"queue":"development.default","priority":100,"run_at":"2015-11-26T23:23:23.374-05:00","job_id":27,"job_class":"Jobs::Sleepy","args":[],"error_count":0},"elapsed":40.08081}
```

**Comment by tpitale** [comment]
So, that log would appear to indicate that different workers are grabbing the jobs … just not running concurrently.

I'm wondering if something else is interacting with que … so going to start a new, clean project.

**Comment by tpitale** [comment]
Does the same thing in a fresh project: https://github.com/tpitale/que-test

Not sure how much simpler I can make it. I might just have the wrong expectation?

**Comment by tpitale** [comment]
Ahhhh … it's the adapter checkout process. If you use just a straight up PG Connection. https://github.com/chanks/que/blob/master/lib/que/adapters/pg.rb#L14-L16

I'll open a PR to add this to the README or Docs, whichever you'd prefer @chanks.

**Comment by tpitale** [comment]
And that fixes it: https://github.com/tpitale/que-test/commit/cd948ce59ad3fc959b3befa25e59efa0efe1a73a

**Comment by tpitale** [comment]
Hey look, it says it right here (derp) https://github.com/chanks/que/blob/master/docs/using_plain_connections.md
