### ISSUE TITLE
v0.11.2 upgraded and not running task anymore

### ISSUE THREAD

**Issue by ryancheung** [chanks/que#139]
Queued tasks do not running anymore after upgrade from v0.11.0 to v0.11.2. 

I use :async mode, which spawns workers on puma thread. It's used to be fine, but broken after upgraded to v0.11.2.

I tried the new `que` bash command to spawn workers in extra process and set mode :off in puma process, this isn't working unless i use the old rake task `rake que:work` to spawning worker process.

BTW, I use the :default que for all my tasks

**Comment by chanks** [comment]
Are you sure that the upgrade is the only thing that changed between working and not working? I just looked at the commit history and nothing between 0.11.0 and 0.11.2 stands out as possibly causing this.

**Comment by ryancheung** [comment]
Yes, I'm sure. In the start, I run que worker in the puma thread(web thread), using the :async mode. Every thing works fine. But after que upgraded to 0.11.2, queued tasks just did not running and stay as queued.

**Comment by chanks** [comment]
How about 0.11.1?

**Comment by benprew** [comment]
@chanks I was running into this issue as well, using the QUE_QUEUE environment variable, although I'm using unicorn.

I think the change is this commit:

3ddc9d904ca5414cc8b8509004f93836aa2a2964

Where previously it was explicitly using the environment variable, and now when Que starts, the workers aren't getting the queue_name passed to them.

Previously my unicorn.rb looked like this:

```
Que.mode = :async
```

But, now it looks like:

```
Que.queue_name = ENV['QUE_QUEUE']
Que.mode = :async
```

And my workers are working the correct queue now.

**Comment by chanks** [comment]
Hmm, alright. I'll be sure to look at this before releasing 0.11.3. In the
meantime, at least the workaround is pretty simple.

Thanks!

**Comment by chanks** [comment]
Now that I'm looking into it, that commit made it into 0.11.0, so it wouldn't explain ryancheung's problem, whatever it was.

Needing to use the environment variable to set up the configuration is a bit awkward, but I think it's a necessary part of wanting to run workers in the web process (that queue_name configuration is done for you if you run workers using the executable). So I added a small note to the docs about it, but I don't think it needs an actual code change.

**Comment by jeffling** [comment]
I have a similar issue. it seems like unless I specify the queue_name in my config. By default, are workers supposed to process all queues?

**Comment by chanks** [comment]
No, by default only the default queue is used, and its name is an empty
string. Specific queue names are generally only used when you need to
distribute certain jobs to certain workers (like to machines with specific
resources). If you want to specify priorities you should use the priority
system.

**Comment by jeffling** [comment]
I see. ActiveJob's recommended default queue name is 'default', which lead to this confusion. Thanks!

**Comment by chanks** [comment]
Closing old issues. The default queue name was changed for 1.0, so this little hiccup shouldn't be an issue anymore.
