### ISSUE TITLE
Work freezes, strange behavior on long jobs

### ISSUE THREAD

**Issue by tpitale** [chanks/que#142]
At seemingly-random times, Que will not finish a job that it's running, and will not take any more jobs to work on. It will stay "frozen" like this until restarted. When restarted it picks right up going again.

It does not appear to be anything due to failed jobs … at least not reliably.

I am using Que for some long-ish jobs. At times, ~30 minutes. Not sure if this is related.

@chanks: if you have any other ideas as to where I might start digging, I'll keep on debugging. But I just wanted to open this for conversation.

Thanks!

**Comment by chanks** [comment]
The first thing I'd do to debug is try to reproduce the freeze, then
inspect the current backtraces on the worker threads to see what they're
doing at the time. If there's a deadlock or something, that'll show it.

Also, in these long running jobs, are you holding transactions open for
long periods of time? That can introduce issues too.

**Comment by tpitale** [comment]
For these particular jobs I'm not holding any transactions.

I'm going to try to attach gdb when it freezes next time. I'm also going to disable all my other job types.

**Comment by joevandyk** [comment]
It might also be helpful to look at what `select * from pg_stat_activity where state != 'idle'` returns.

**Comment by tpitale** [comment]
Nothing at all in `pg_stat_activity`. Not sure if that's good or bad :wink:

**Comment by tpitale** [comment]
This is very hard to reproduce. I just have to _wait_ until it happens. I have no idea what's triggering it, so can't reproduce at will, yet.

**Comment by joevandyk** [comment]
If it happens again, check pg_stat_activity (unless you previously checked
it while experiencing the problem)

**Comment by tpitale** [comment]
@joevandyk Nothing in there when the problem happened the most recent time. Then I tried to attach with gdb and it just killed the process (probably my own fault).

**Comment by tpitale** [comment]
Is it possible that, given there is nothing in `pg_stat_activity` for the workers, that it's simply failing to reconnect after losing connection to postgresql?

Possibly similar to https://github.com/chanks/que/issues/130? Except, in my case, I would prefer it crash. Rather than just hanging around doing nothing.

I've tested this by killing my database while que is running (but not working a job) … and it doesn't crash … but never reconnects to the database, and will happily run along doing nothing at all, no matter which jobs get added.

**Comment by tpitale** [comment]
For more information, I'm using the connection_pool gem (after a previous issue involving my ignorance). So, it may be that connections don't get dropped by the connection pool if they losing connection to the database?

**Comment by tpitale** [comment]
This could also be the same as: #93. I'll investigate.

**Comment by tpitale** [comment]
This may be a distinct issue, but this is what logs say after postgres restarts:

```
I, [2016-02-03T14:41:55.398713 #17532]  INFO -- : {"lib":"que","hostname":"tasty-server","pid":17532,"thread":70079062359120,"event":"job_errored","error":{"class":"PG::AdminShutdown","message":"FATAL:  terminating connection due to administrator command\nSSL connection has been closed unexpectedly\n"},"job":null}
I, [2016-02-03T14:41:55.422788 #17532]  INFO -- : {"lib":"que","hostname":"tasty-server","pid":17532,"thread":70079062401780,"event":"job_errored","error":{"class":"PG::ConnectionBad","message":"PQsocket() can't get socket descriptor"},"job":null}
I, [2016-02-03T14:41:56.396298 #17532]  INFO -- : {"lib":"que","hostname":"tasty-server","pid":17532,"thread":70079062359120,"event":"job_errored","error":{"class":"PG::ConnectionBad","message":"PQsocket() can't get socket descriptor"},"job":null}
I, [2016-02-03T14:41:56.423100 #17532]  INFO -- : {"lib":"que","hostname":"tasty-server","pid":17532,"thread":70079062401780,"event":"job_errored","error":{"class":"PG::ConnectionBad","message":"PQsocket() can't get socket descriptor"},"job":null}
```

And it never tries to reconnect, until the process is restarted.

**Comment by chanks** [comment]
That seems possible, since Que offload a lot of the responsibility for handling the connection pool. I think most people use Que with ActiveRecord or Sequel, which have their own facilities for handling bad connections, but I guess using connection_pool you wouldn't have that ability built in.

I don't like the idea of having a lot of extra logic for detecting bad connections and opening new ones. I wonder whether that functionality would be best wrapped up into a new gem? One similar to connection_pool (or pond, which I'm partial to because I wrote it), and which maybe even relies on connection_pool/pond, but can recognize and handle failed connections.

**Comment by tpitale** [comment]
@chanks Great. Totally agree that Que should not need to be concerned about that. I personally use DataMapper, so maybe I'll try to make an adapter for that in my own project (since DM is basically dead). If that doesn't work, which it might now, I'll take a look at what connection_pool does with dead connections.

**Comment by chanks** [comment]
Ah, I see. Yeah, it's not really ideal to use a different connection pool for Que than the one the rest of your app uses, since then jobs enqueued in Que aren't covered by the transactions that the rest of your app is using.

If you ever decide to tackle moving off of Datamapper, I strongly recommend Sequel, it's basically my favorite gem :blush: but if your app is too enmeshed in Datamapper, that's totally understandable.

**Comment by tpitale** [comment]
I definitely use Sequel a lot. Just the amount of work is daunting.

I admit the transactional benefits are not a feature I needed from Que, so I'm not too worried about that part.

ConnectionPool/Pond both seem to be generic (they show Redis as their examples). So, does make it difficult to say how they would clear/remove dead connections from their pools.

If you'd be open to it in pond, there could be a hook (block) before checking in a connection that asks if it's dead/closed/finished. Then the user could configure a block for that, at which point the connection would be dropped from the pool. I'd be happy to send a PR for that too Pond.

**Comment by chanks** [comment]
I actually thought I remembered implementing something like that in Pond, and it turns out I did! But I didn't merge it to master, and now I don't remember why :-/

https://github.com/chanks/pond/compare/detach-on-checkin

**Comment by tpitale** [comment]
That's definitely a way to do it.

**Comment by chanks** [comment]
Alright, well, Friday is my open source day at work (sometimes :stuck_out_tongue:) so I'll look over that branch of Pond then and maybe merge it. Or if you come up with a PR for Pond or Que I'd be happy to look at it then too.

**Comment by tpitale** [comment]
I have an idea for how to do it … that may be useful. I could see this approach as well as another:

$pond = Pond.new(…) {PG.connect(…)}
$pond.detach_if = lambda {|connection| connection.finished?}

Then Que adapter don't need to be changed.

But, this doesn't handle cases of error/exceptions. Though, in the case of PG that won't matter because it'll be closed/finished regardless.

**Comment by tpitale** [comment]
If that approach is useful, I can send a PR today.

**Comment by chanks** [comment]
Yeah, I think the callback function probably makes more sense :)

**Comment by tpitale** [comment]
Spike: https://github.com/chanks/pond/pull/2

**Comment by tpitale** [comment]
Okay, back to the original issue:

@joevandyk I'm seeing this in `pg_stat_activity` now that I've found another frozen situation:

```sql
SELECT 1 AS one                  
FROM   que_jobs                  
WHERE  queue    = $1::text       
AND    priority = $2::smallint   
AND    run_at   = $3::timestamptz
AND    job_id   = $4::bigint     
```

The state is `idle`. The query was started at 5:32 AM UTC, so about  10 hours ago.

**Comment by joevandyk** [comment]
idle connections in postgresql are fine -- if something opens a connection
runs a query once and doesn't do anything, it will show up as an idle
connection.  So in this case, the job query started and finished 10 hours
ago. But there wasn't any more job queries since then.

**Comment by tpitale** [comment]
I went digging through the logs, which are unfortunately being logrotated. The worker was running long enough that the Rails.logger got rotated into a gzipped file. I needed to add `copytruncate` to all my configs for logrotate. Starting again to wait for freezing/lockup and I'll continue debugging.

**Comment by tpitale** [comment]
@joevandyk So, it's "stopping" in the middle of a job (not picking up any new jobs, not querying for new jobs), but … it's also not crashing.

Does that narrow down where I should look inside Que? Maybe into the worker class itself?

**Comment by joevandyk** [comment]
Does Que.job_stats report the job is running?

**Comment by chanks** [comment]
Yeah, this is why I suggested trying to reproduce it locally and look at
what the worker threads were doing. It could be something inside Que, it
could be something inside your job, it could be something inside a
library your job is using... Getting the last thing the connection executed
is easier but not that helpful in this case :-/

**Comment by tpitale** [comment]
Yeah, it's the reproducing part that's the issue. I don't know what's causing it to do this. Just trying to narrow it down. I can't trigger the freeze, yet.

**Comment by tpitale** [comment]
I've added Que.job_stats to my reporting. Will see what it says the next freeze.

**Comment by tpitale** [comment]
I'm now 99.9% sure that it's something within my job that is freezing due to network disconnection that is not causing a failed job. Closing unless I find evidence otherwise.

**Comment by joevandyk** [comment]
Have you tried adding a timeout to the job that raises a noisy exception if
it takes more than, say, 5 or 10 minutes? That would probably let you
pinpoint what's taking so long.

**Comment by chanks** [comment]
Ok, thanks Tony! Sorry it's taken so long to figure this out.

**Comment by tpitale** [comment]
No worries @chanks, clearly not your fault at all. Appreciate you bearing with me.

**Comment by tpitale** [comment]
@joevandyk suggested way to add a timeout? I don't think I can use ruby's fairly unreliable timeout library. I'm not aware of Que allowing setting a max run time for a job/worker. Unless I'm missing something there.

**Comment by joevandyk** [comment]
Being able to set a timeout on jobs would indeed by nifty. 

For debugging purposes, I would think something like:

```
begin
  Timeout.timeout(some_time) do 
    # run job 
  end
  rescue Timeout::Error 
    # Log
    exit 1
  end
end
```
might work

**Comment by chanks** [comment]
Yeah, I don't know a way to set timeouts on jobs generally aside from the timeout library, which has issues.

One enhancement to Que that I've thought about in the past is to set up a signal handler that would cause the current backtrace of every worker to be output to the logger. That might have made tracking down the initial problem here a lot faster. Haven't had time to work on it though.
