### ISSUE TITLE
Rails 5 issues

### ISSUE THREAD

**Issue by ollym** [chanks/que#143]
```
{"class":"NoMethodError","message":"undefined method `before_committed!' for #\u003cQue::Adapters::ActiveRecord::TransactionCallback:0x007fe849b993b0\u003e"}
```

This doesn't when `Que.mode = :sync`

**Comment by chanks** [comment]
That's interesting. I didn't write the integration with ActiveRecord's transaction logic, and really don't use Rails at all anymore, but I'd certainly accept a patch if anyone wants to take a crack at this. Though I imagine it would better belong in the dedicated que-rails gem, if that ever gets off the ground.

**Comment by joevandyk** [comment]
https://github.com/chanks/que/pull/144

**Comment by ollym** [comment]
Thanks, @joevandyk 

Until this makes it as a release, here is a quick fix as an initilizer:

```ruby
# config/initilizers/fix_que_for_rails5.rb

class Que::Adapters::ActiveRecord::TransactionCallback

  def before_committed!(*)
    # no-op
  end
end
```

**Comment by chanks** [comment]
#144 merged!
