### ISSUE TITLE
Travis CI failing on master and all PRs

### ISSUE THREAD

**Issue by tpitale** [chanks/que#146]
This may be related: https://github.com/bundler/bundler/pull/3559

Which was merged in April of 2015. Seems like it should be available and in use by Travis. I'll investigate further.

In case we need to, it seems we might be able to configure bundler version: https://docs.travis-ci.com/user/languages/ruby#Custom-Bundler-arguments-and-Gemfile-locations

**Comment by chanks** [comment]
Closing old issues. We've since migrated to CircleCI with a fairly custom setup.
