### ISSUE TITLE
job_id is always 0

### ISSUE THREAD

**Issue by alistairholt** [chanks/que#148]
Hello,

I'm running Que in production and after having to investigate an issue which may or may not be related to Que I've noticed that all jobs in Que's database table have a `job_id` of `0`. Is this normal?

Output from the app below:

```
["priority", "run_at", "job_id", "job_class", "args", "error_count", "last_error", "queue"]
["100", "2026-04-15 19:56:38.886564", "0", "ResumeSubscriptionJob", "[1]", "0", nil, ""]
["100", "2026-04-15 19:57:13.701706", "0", "ResumeSubscriptionJob", "[2]", "0", nil, ""]
["100", "2016-05-12 09:03:30", "0", "ResumeSubscriptionJob", "[123]", "0", nil, ""]
["100", "2016-04-18 14:53:12", "0", "ResumeSubscriptionJob", "[38]", "0", nil, ""]
["100", "2016-06-10 16:31:14", "0", "ResumeSubscriptionJob", "[126]", "0", nil, ""]
```

Thanks!

**Comment by chanks** [comment]
That's definitely unusual. Can you look at your Postgres schema and make sure that the default for the job_id column is still nextval() on the appropriate sequence?

**Comment by alistairholt** [comment]
Thanks for the prompt reply. Somehow it has ended up as `not null default 0` in production. Here's the line from my `schema.rb`:

`t.integer  "job_id",      limit: 8, default: "nextval('que_jobs_job_id_seq'::regclass)", null: false`

**Comment by chanks** [comment]
Oh, you're using Rails, so you'll need to set your schema_format to :sql. There's a link to more information in the README. :smile:

**Comment by alistairholt** [comment]
A serious case of RTFM 😳. Sorry for wasting your time! Thanks for your help.
