### ISSUE TITLE
Support job middleware

### ISSUE THREAD

**Issue by joevandyk** [chanks/que#149]
I'd love to see something like https://github.com/mperham/sidekiq/wiki/Middleware supported in que. Overriding _run is sorta hacky I think.

**Comment by chanks** [comment]
I actually think that overriding methods and calling super() is one of the more elegant and Ruby-ish ways to customize behavior. In the case of Job classes, prepending a module that overrides `run` is probably nicer than making a new subclass that overrides `_run`, though.

**Comment by chanks** [comment]
Closing old issues - I'm still a believer in overriding job behavior via the module system, but master (the 1.0 beta) does support defining middleware that will wrap all jobs.
