### ISSUE TITLE
[Proposal] Update the docs on inspecting the queue regarding ActiveRecord

### ISSUE THREAD

**Issue by texpert** [chanks/que#150]
Hello, @chanks!

There is a gem to use composite primary keys - https://github.com/composite-primary-keys/composite_primary_keys, so the docs could be updated to something like that:

Gemfile:
```
gem 'composite_primary_keys', '>=9.0.0.beta1' # This is for Rails 5.0.0.beta3 and higher
```

Your model file:
```
class QueJob < ApplicationRecord
  self.primary_keys = :queue, :priority, :run_at, :job_id
end
```

And then you can update the queue, but only via update_all method (BTW with example for searching json array for attributes):
```
  def update_que(status, schedule)
    job = QueJob.where("args::json->>0 = '?' AND args::json->>1 = ?", booking.id, status)
    job.update_all(run_at: schedule)
  end
```

**Comment by joevandyk** [comment]
Hm, usually you should be able to do QueJob.find(job_id) and expect it to
work fine. There's no database constraint on it, I suppose.

**Comment by joevandyk** [comment]
This is what we do:

```
class QueJob < ActiveRecord::Base
  self.primary_key = :job_id
end
```

**Comment by chanks** [comment]
I don't think we should have sections in the docs for how Que might interact with other gems, unless they're so ubiquitous that we're going to get lots of questions about them. This might make a good blog post for you to write, though - that way anyone with this problem could find it with a quick google search.

**Comment by Easy-D** [comment]
Just one question regarding the code posted above:
```ruby
def update_que(status, schedule)
  job = QueJob.where("args::json->>0 = '?' AND args::json->>1 = ?", booking.id, status)
  job.update_all(run_at: schedule)
end
```
Would it be safe to update `run_at` like that, or do we need to acquire a lock before? IIRC, Que's `destroy` method might fail in that case.

**Comment by texpert** [comment]
@joevandyk , thank you! The search and update is working indeed with a single primary key.

@Easy-D, have not tried destroy yet. As for safety of updating run_at, let's ask @chanks !

**Comment by chanks** [comment]
Updating jobs like that won't be safe if they're running, since they won't be found and destroyed, so they may run twice. If that's not a problem, though, go ahead. Or just update the run_at on jobs where the run_at is still in the future.
