### ISSUE TITLE
job raising NotImplementedError kills worker

### ISSUE THREAD

**Issue by prognostikos** [chanks/que#152]
Usually when exceptions are raised in `JobClass#run` que happily retries, as expected.

Today, however, I was able to crash the worker by raising NotImplementedError:

Version 0.11.4 on ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

```
app/worker.1:  /app/app/jobs/my_job.rb:5:in `run': NotImplementedError (NotImplementedError) 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/que-0.11.4/lib/que/job.rb:17:in `_run' 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/que-0.11.4/lib/que/job.rb:102:in `block in work' 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/que-0.11.4/lib/que/adapters/active_record.rb:7:in `block in checkout' 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection' 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/que-0.11.4/lib/que/adapters/active_record.rb:54:in `checkout_activerecord_adapter' 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/que-0.11.4/lib/que/adapters/active_record.rb:7:in `checkout' 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/que-0.11.4/lib/que/job.rb:85:in `work' 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/que-0.11.4/lib/que/worker.rb:80:in `block in work_loop' 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/que-0.11.4/lib/que/worker.rb:75:in `loop' 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/que-0.11.4/lib/que/worker.rb:75:in `work_loop' 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/que-0.11.4/lib/que/worker.rb:19:in `block in initialize' 
app/worker.1:  /app/app/jobs/my_job.rb:5:in `run': NotImplementedError (NotImplementedError) 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/que-0.11.4/lib/que/job.rb:17:in `_run' 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/que-0.11.4/lib/que/job.rb:102:in `block in work' 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/que-0.11.4/lib/que/adapters/active_record.rb:7:in `block in checkout' 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection' 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/que-0.11.4/lib/que/adapters/active_record.rb:54:in `checkout_activerecord_adapter' 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/que-0.11.4/lib/que/adapters/active_record.rb:7:in `checkout' 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/que-0.11.4/lib/que/job.rb:85:in `work' 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/que-0.11.4/lib/que/worker.rb:80:in `block in work_loop' 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/que-0.11.4/lib/que/worker.rb:75:in `loop' 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/que-0.11.4/lib/que/worker.rb:75:in `work_loop' 
app/worker.1:  	from /app/vendor/bundle/ruby/2.3.0/gems/que-0.11.4/lib/que/worker.rb:19:in `block in initialize' 
heroku/worker.1:  State changed from up to crashed 
heroku/worker.1:  Process exited with status 1
```

From a quick glance at the code this does not seem to be expected behavior, but I could be wrong?

**Comment by joevandyk** [comment]
http://ruby-doc.org/core-2.2.0/ScriptError.html
http://ruby-doc.org/core-2.2.0/NotImplementedError.html

I don't know if NotImplemented errors should be caught, seems like a pretty
weird thing to be looking for. But if they are, possibly ScriptError should
be caught instead.

**Comment by chanks** [comment]
Yeah, NotImplementedErrors apparently don't descend from StandardError so they aren't covered by the generic rescue clause. Interesting. Learn something new every day, I guess.

I agree with Joe that it'd be weird to single them out for rescue, especially since you should never see them in production, only in development and test. So I'm inclined to call this a WONTFIX, unless someone has a compelling argument for it.

**Comment by prognostikos** [comment]
No worries - I agree it's fine to only rescue StandardError. Didn't think to check the exception hierarchy - nice find.

**Comment by ZimbiX** [comment]
We ran into this a couple of days ago. TIL you're not supposed to use `NotImplementedErrors` like we were! http://chrisstump.online/2016/03/23/stop-abusing-notimplementederror/

**Comment by ZimbiX** [comment]
Most surprisingly, we did not even see the error in Sentry, and only noticed later that our Kubernetes pods were in a CrashBackOffLoop. It turns out that even though we were capturing errors in our `Que.error_notifier` proc, that only gets called for exceptions which inherit from `StandardError` - `rescue`'s default: https://github.com/que-rb/que/blob/94fee90195cdb38e946129e102a81a070692f952/lib/que/worker.rb#L125-L136
