### ISSUE TITLE
ActiveJob and Que arguments compatibility issue

### ISSUE THREAD

**Issue by clamoris** [chanks/que#156]
Since Que using HashWithIndifferentAccess as default json converter symbol hash keys and named arguments do not work with ActiveJob. 

ActiveJob use transform_keys to deserialize symbol keys

```
# activejob/lib/active_job/arguments.rb

def transform_symbol_keys(hash, symbol_keys)
  hash.transform_keys do |key|
    if symbol_keys.include?(key)
      key.to_sym
    else
      key
    end
  end
end
```

BUT

```
{ "foo" => 1 }.with_indifferent_access.transform_keys(&:to_sym) # => {"foo"=>1}
```

So jobs like 

```
class AwesomeJob < ActiveJob::Base
  def perform(params)
    # code using params[:foo]
  end
end
```

will fail with no obvious reason

**Comment by chanks** [comment]
Another reason to not use ActiveJob. There have been a few others, if you search the issues.

Does everything work as expected if you set `Que.json_converter = Que::SYMBOLIZER` instead? If so, I think the correct fix is probably to just document that, or to add it to the ActiveJob Que adapter.

**Comment by clamoris** [comment]
@chanks `Que.json_converter = nil` works fine

**Comment by chanks** [comment]
Closing old issues. This should no longer be a problem, our ActiveJob integration is much better (and better-tested!) now.
