### ISSUE TITLE
Use postgresql 9.5 features: "skip locked" row-level locking

### ISSUE THREAD

**Issue by riddochc** [chanks/que#158]
I just discovered Que a couple weeks ago, and earlier today was looking through this year's PGCon talks, which included one on using PostgreSQL for managing job queues, slides are here: http://www.pgcon.org/2016/schedule/attachments/414_queues-pgcon-2016.pdf

Slide 34 may be of interest here, it shows using the new "skip locked" feature for dequeueing jobs.

The comments at the top of lib/que/sql.rb here suggest that the purpose of the CTE in lock_job is to avoid locking multiple jobs in the process of finding one to lock and work on.  That's quite a subtle work of SQL... Perhaps the technique described in this talk would simplify things?

I could get around to experimenting with this, but I think figure this is worth mentioning here in case someone else happens to get around to it before I do.

**Comment by chanks** [comment]
Yeah, I've known about it for a while, but haven't planned to do anything with it. It's only useful with FOR SHARE/UPDATE locks, which are only good for the length of the transaction. Which means you'd either need to work the entire job while the transaction is held open or use it as part of a larger query that updates the row to mark it as being reserved. The first would make Que a poor choice for jobs that take too long to run, the second would complicate the issue of how to release jobs if a worker crashes. Either you need to assume that a job that's been locked more than a given period of time is open for business again, which is iffy, or you need to do something more complex to have the worker check in every so often (I believe queue_classic does something like this). It also turns the job-lock query into a disk write, which is less efficient than just taking an advisory lock.

It'll be a great tool for something like queue_classic, though, and I'm curious to hear how it works out for them. If there's some locking mechanism that uses it and skirts these issues that I don't know of, though, please let me know.

**Comment by riddochc** [comment]
Hmm. My intuition is that there's some options for handling transactions
and concurrency that could address at least some of these issues, but I'm
not really sure off the top of my head. I'll find some time to read up on
the relevant sections of the postgresql documentation and let you know if I
find something interesting for this.

In the meantime, thanks for Que. It's helped me clean out a few unnecessary
dependencies from a pioject.

On Tuesday, June 14, 2016, Chris Hanks <notifications@github.com> wrote:

> Closed #158 <https://github.com/chanks/que/issues/158>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/chanks/que/issues/158#event-692064283>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAAaSUlni0k4-lVeRi3OV16pX4EdQnGcks5qLtIygaJpZM4I03FY>
> .
>


-- 
Chris Riddoch
http://www.syntacticsugar.org/

**Comment by MichaelSnowden** [comment]
I have a question about how Que works because I’m interested in porting it to Go, and all the other forks seem to use the SKIP LOCKED approach with one of the 2 flavors below.

> It's only useful with FOR SHARE/UPDATE locks, which are only good for the length of the transaction. Which means you'd either need to work the entire job while the transaction is held open or use it as part of a larger query that updates the row to mark it as being reserved. The first would make Que a poor choice for jobs that take too long to run, the second would complicate the issue of how to release jobs if a worker crashes.

Can you explain how Que works around this with advisory locks? I assume Que creates a connection to PG which holds the lock and PG knows to unlock it when that connection dies, but how do you do this without creating a long-running transaction? And what happens if that connection dies without a crash, so the job is still being worked on?

Thanks and please let me know if there’s a better forum for this question!

**Comment by chanks** [comment]
> I assume Que creates a connection to PG which holds the lock and PG knows to unlock it when that connection dies

This is correct.

> but how do you do this without creating a long-running transaction?

There are two types of advisory locks, session-level and transaction-level. Transaction-level are released when the current transaction resolves, but Que uses session-level ones, which don't need a transaction. See [the Postgres docs](https://www.postgresql.org/docs/14/functions-admin.html#FUNCTIONS-ADVISORY-LOCKS)) for more info.

> And what happens if that connection dies without a crash, so the job is still being worked on?

I haven't looked at the Que code in a while, but I don't think this was a failure mode I had in mind when I designed 1.0. It seemed unlikely, but I guess you could get there with a `pg_terminate_backend`. Not sure what the ideal approach would be, here - assuming that the thread holding the connection knows when the connection is lost (an error is thrown or something) it could try to reestablish the connection and re-lock all the jobs it took, but that wouldn't guarantee that another worker hadn't picked any of them up in the meantime. If you're worried about it, I guess that's something that writing a "worker_id" value to the job would help with.
