### ISSUE TITLE
Que are failing on :off mode and are running in web process for :async mode

### ISSUE THREAD

**Issue by przbadu** [chanks/que#159]
I am loving `que` gem and what it does, it is working great for my need and was working perfectly on `heroku` until I change my mind to split `que` jobs to seperate workers (I have lots of import/webhooks going on). I am now struggling on how to seperate `web` and `worker` process, so that workers load don't effect my web part.

Below are my configuration:

`config/initializers/que.rb`

``` ruby
Que.wake_interval = 10.seconds
# Que.mode = (ENV['QUE_MODE'] or Rails.env.production? ? :async : :off).to_sym
Que.mode = :off
Que.worker_count = (ENV['QUE_WORKERS'] || 1)
```

`Procfile`

``` ruby
web: bin/rails server -p $PORT -e $RAILS_ENV
worker: bundle exec rake que:work
```

Previously, when I had only one `web` process in heroku and `Que.mode = :async` `que` was running successfully within same `web` process.

Now that I setup seperate `worker` process for it, I tried using `Que.mode = :off` and I can't see any que logs, and I can see all the failing jobs in `que-web`.

Please let me know what I am missing, and which mode will be suitable in my configuration. 

**NOTE**: I want to keep `web` and `worker` process seperate and `worker` should be responsible for running my `que jobs`.

**Comment by przbadu** [comment]
As soon as I turned `Que.mode = :async` and deploy to heroku, it starts running Que in web process itself.

I did this configuration in `Procfile` now:

web: QUE_MODE=:off bin/rails server -p $PORT -e $RAILS_ENV
worker: QUE_MODE=:async bundle exec rake que:work

now, it did set `web` process and now I can't see import script running neither in `web` nor `worker`.

**Comment by prognostikos** [comment]
@przbadu here's what's working for me on Heroku with que 0.11.5:

`config/initializers/que.rb`

```
Que.wake_interval = 1
```

`Procfile`

```
web: bin/web
worker: bin/que ./config/environment.rb
```

There have been some changes to defaults, in particular checkout https://github.com/chanks/que/blob/master/CHANGELOG.md#0110-2015-09-04 from the changelog.

**Comment by chanks** [comment]
Closing some old issues. I'm not clear on what the original problem was, but there is a CLI now that's the recommended way to work jobs.
