### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by sheerun** [chanks/que#162]
@chanks I've just encountered presentation of Thomas Munro from PGConf that lists possible improvements on top of advisory locks. Could you take a look?

https://www.pgcon.org/2016/schedule/attachments/414_queues-pgcon-2016.pdf

**Comment by chanks** [comment]
I skimmed it quickly but didn't really discover anything I wasn't aware of. SKIP LOCKED is new but I don't think it's an inherently better technique - see #158 for discussion.

Was there something specific in that presentation that you thought was worth using?

**Comment by sheerun** [comment]
Maybe creating NOTIFY channel for each connected worker and make each worker to LISTEN to its channe (and ping random worker if job is available). This could be functionality on top of current mechanism, to prevent unnecessary queries when there are no jobs (most of the time?)

**Comment by chanks** [comment]
The 1.0 branch does basically that. I haven't had time to work on it recently, though.

**Comment by chanks** [comment]
It's almost a total rewrite, btw, so don't expect to be able to just start using it without issues.

**Comment by sheerun** [comment]
ok then :)
