### ISSUE TITLE
Run in application thread

### ISSUE THREAD

**Issue by mystdeim** [chanks/que#163]
If I use `Job.perform_later` it will run in application thread, but if I set simple `Job.set(wait: 1.seconds).perform_later` it's ok and run in the que

**Comment by chanks** [comment]
I don't know what you're using, but it doesn't sound like Que.

**Comment by mystdeim** [comment]
I use Active Job from rails and Que as adapter for it

**Comment by chanks** [comment]
You'll need to talk to ActiveJob about it, then.
