### ISSUE TITLE
Multiple queues

### ISSUE THREAD

**Issue by mystdeim** [chanks/que#165]
Can I run one queue with 1 worker and run other queue with multiple workers. I want that in first queue task executes only one at the same time

**Comment by chanks** [comment]
This isn't a bug, please only use Github issues for bugs or concerns with the library. If you need help on how to use it, try posting on que-talk (https://groups.google.com/forum/#!forum/que-talk), but if your question is something that could be figured out by reading the docs, people may not be running to answer you.
