### ISSUE TITLE
Document an example of using que with gem shrine

### ISSUE THREAD

**Issue by alfamemoria** [chanks/que#169]
It would be great if we have a working example of using que with the new gem shrine to upload videos and photos. There is only an example with Sidekiq. Thanks!

**Comment by chanks** [comment]
I really only see the value of including examples like that in the docs if 1) the usage is generic enough that most people would find it helpful (so it's not tied to a specific gem) and 2) the implementation using Que is somehow different from what the implementation would be with a different job queue. If you really think that an example of using Que with Shrine specifically would be helpful to people, might I recommend a blog post?

**Comment by janko-m** [comment]
@alfamemoria The beauty of Shrine's backgrounding design is that you're calling the backgrounding job directly. This means that you just have to look at the docs for the backgrounding library you're using (Que) to find out how job classes are called and defined 😉 

```rb
Shrine::Attacher.promote { |data| PromoteJob.enqueue(data) }
Shrine::Attacher.delete { |data| Delete.enqueue(data) }
```
```rb
class PromoteJob < Que::Job
  def run(data)
    Shrine::Attacher.promote(data)
  end
end
```
```rb
class DeleteJob < Que::Job
  def run(data)
    Shrine::Attacher.delete(data)
  end
end
```
