### ISSUE TITLE
Q: Latency

### ISSUE THREAD

**Issue by jrochkind** [chanks/que#174]
I really like que's design and implementation, in a number of ways. I like that you can run it in-process in :async mode. 

But I have a use case where I need extremely low latency -- if a job is queued, and there are non-busy worker threads, I want them to start working on the job as quickly as possible. Ideally miliseconds, maybe tens of miliseconds, but definitely not seconds. This is because I have some client web pages polling to see if the work is done, to update the UI.  I think I get this with, say, redis/sidekiq. 

I guess I could set `wake_interval` to something very low, even something less than `1`.  `.01`? `.001`?  I'm not sure if this would have disastrous effects on performance or not. I'm also not sure what the net effect would actually be, in the case where there are a bunch of idle threads, and a bunch of work comes in at once, along the lines of your note about `wake!` vs `wake_all!`. 

Alternately, if I'm running workers in-process, I suppose every single time I queue a job, i could call `wake!`.  I'm not sure if this would have negative effects on performance, including possibly effecting the performance of the host app. 

And that fails if I'm running workers in an external process instead. Hypothetically, one could imagine some kind of use of postgres listen/notify, where every time a job is queued a 'notify' is done, and then something in the other process is 'listen'ing and does a `wake!` or `wake_all!` on notification -- but this starts to seem kind of convoluted and with possibly dangerous effects. 

Any thoughts on the best way to use que to ensure low-latency in picking up jobs?

**Comment by joevandyk** [comment]
If you don't have a ton of workers, like more than 20, then setting
wake_interval to something low should work fine. It's a really fast query.

**Comment by chanks** [comment]
You can try the 1.0 branch if you're feeling very adventurous, it uses
listen-notify. It's running in a staging/QA environment for an upcoming
product at my day job. I wasn't planning on having it reach 1.0 final for a
while, though, and though it seems relatively stable I haven't actually
been too hard on it yet, so of course I make no guarantees!

You're probably better off sticking with a low wake_interval or using wake!
for now, though. And whether the low wake_interval causes a problem will
depend on your number of workers and your DB hardware.

**Comment by jrochkind** [comment]
Thanks for the advice. Do you think the 1.0 branch with listen/notify would deal with latency better, then? I was kind of just guessing about listen/notify helping, and it prob depends on how it's deployed/implemented exactly.

**Comment by chanks** [comment]
Yeah, it should mean that the fact that there's a new job will be pushed to
a worker process immediately, without the need for polling. Polling still
exists, since it's the only way to catch retries and jobs scheduled in
advance, but it locks jobs in batches now, rather than one at a time.

**Comment by chanks** [comment]
Closing this, since 1.0 is in beta release now.
