### ISSUE TITLE
Handling a lot of data with Que

### ISSUE THREAD

**Issue by bbozo** [chanks/que#175]
Hi all :)

I am using Que with the [Sequel][2] gem, I am interested if it is safe to write jobs that need to handle a lot of data, too much data than what can be safely placed in 1 database transaction, such as import/export of 80k+ rows on a regular basis (I currently process records in 1k record transaction batches).

The thing I'm concerned about is if the gem/postgres does some kind of implicit transaction around the background worker execution which would potentially make the rollback segment go out of hand and crash the DB down in a swappy hell.

The reason why I'm asking this is, this line from the docs:

> Safety - If a Ruby process dies, the jobs it's working won't be lost, or left in a locked or ambiguous state - they immediately become available for any other worker to pick up.

with me this screams "nested in a transaction", which if my fears are true could potentially result in silently wrapping my 80k records into the same rollback segment. I could try it on my laptop, but my laptop is far stronger then the production VM so I'm afraid it might successfully crunch on my dev environment and then gloriously crash in deployment.

Can someone with similar experience help out?

PS [SO question](https://stackoverflow.com/questions/40215391/is-que-safe-for-writing-jobs-that-handle-a-lot-of-data)
PPS the new [Que SO tag](https://stackoverflow.com/questions/tagged/que)

  [2]: http://sequel.jeremyevans.net/

**Comment by chanks** [comment]
Hi -

There's no implicit transaction around each job - that guarantee is offered by locking the job id with an advisory lock. Postgres takes care of releasing the advisory lock for us if the client connection is lost, regardless of transactional state.

This isn't an issue with the gem so I'm going to close it - if you just need guidance on an issue I'd recommend posting to the que-talk google group (https://groups.google.com/forum/#!forum/que-talk).
