### ISSUE TITLE
Is there a way to throttle concurrent jobs?

### ISSUE THREAD

**Issue by jemminger** [chanks/que#177]
I frequently get large spikes (thousands) in the number of jobs present, and it seems to starve the connection pool (100).  Is there a way to ensure that no more than 100 jobs are trying to run at once?

**Comment by joevandyk** [comment]
There's a worker count option you can set.

**Comment by chanks** [comment]
Yeah, the worker_count options is how you'd do this, but since it defaults to 4, I'd guess that either you've already set it very high, or something else is going on that is preventing connections being returned to the pool?

**Comment by jemminger** [comment]
Hmm, our QUE_WORKERS is set to 4.  Is it necessary with Que to manually return connections, like it is with sucker_punch?  E.g.

    ActiveRecord::Base.connection_pool.with_connection do
      user = User.find(user_id)
      user.update(is_awesome: true)
    end

**Comment by chanks** [comment]
It usually shouldn't be, but we had a problem a while back with someone who
was connecting to multiple DBs with ActiveRecord and their connections
weren't being cleared properly. Are you doing anything like that?

**Comment by jemminger** [comment]
No, just one postgres db.  Running on heroku, not that that should make any difference?

**Comment by chanks** [comment]
Let's back up a bit, what's the error you're getting, and when? If your pool has a maximum of 100 connections and you're getting an error because things try to surpass that, it seems to me that either 1) your total number of web and worker threads in the same process is over 100 or 2) something somewhere is leaking ActiveRecord connections. And Que already tries to clear all its connections when it's done with a job (https://github.com/chanks/que/blob/07f74f25cc1432acc84a857d2b356ec5c9a37d48/lib/que/adapters/active_record.rb#L20-L30), so unless the ActiveRecord API has changed or something, it shouldn't be that.

**Comment by jemminger** [comment]
The exception I get is "ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)".  This is being thrown from a route in our system that acts as a webhook endpoint for a third-party API.  This controller action simply enqueues a Que job and returns `head :ok`.  The exception is thrown before any application code is hit though.

I'm not sure if it is Que after all.  Since Que defaults to 4 jobs at a time and we haven't changed that, it might be more likely that a spike in requests to this route exhausts the db pool?

**Comment by chanks** [comment]
Ah, yeah, the limit of 4 only applies to the worker pool, which is a separate matter. If it's happening when you try to enqueue a job, that's a separate issue. In that case Que will just try to use the current ActiveRecord connection, just like any ActiveRecord create or update or destroy call would.

It's not clear to me from that error whether you're hitting the limit of the connections that ActiveRecord has available in that process or the limit of connections that heroku allows you to make to its DBs. If it's the former you can probably just bump up the maximum connections configuration option to equal the number of threads you have servicing web requests. If it's the latter you'll probably need to upgrade to a larger Heroku DB.
