### ISSUE TITLE
Multiple queues at once?

### ISSUE THREAD

**Issue by dts** [chanks/que#178]
It looks like it would be easy to support querying of multiple queues at a time, by changing the `=` to a `IN` in the SQL query.  Since gems I depend on insist on having their things in different queues, this would simplify my production environment (right now I have to put them all in separate runners).  Stretch goal: add so that different queues have different priorities in this system.

**Comment by prognostikos** [comment]
@dts I actually came here to ask the same question, but it looks like it's already been discussed on #71

**Comment by prognostikos** [comment]
For what it's worth, as my issue was related to ActiveJob in Rails 4.2, I added the changes from rails/rails#19498 as a freedom patch for my app. Looks like it only made it into Rails 5.

**Comment by dts** [comment]
Thanks for that! I have no idea how I missed that.  I'll hop in there and talk about my use case & proposed solution.

[ ending because #71 ]
