### ISSUE TITLE
Does Que work on multiple hosts?

### ISSUE THREAD

**Issue by qrush** [chanks/que#180]
Hey, a quick question that I can't seem to find an answer to in the docs: Is it safe to run Que workers on more than one machine working off the same database? I'm seeing no documentation regarding or confirming that. I was reading the [job worker code](
https://github.com/chanks/que/blob/master/lib/que/job.rb#L105-L123) and the comment about "session level" locks seems to say to me otherwise.

Thanks! 🙇 ❤️

**Comment by chanks** [comment]
Yes, absolutely! The "session" referred to is the Postgres connection, and Postgres handles the lock interactions between multiple connections. So it doesn't really matter how your worker threads are distributed across processes or physical machines, so long as they're all connecting to the same DB.

**Comment by qrush** [comment]
OK cool, thanks @chanks. I'll get a PR for putting this in the README so it's clear.

**Comment by chanks** [comment]
Alright, cool, I'll close this until then.
