### ISSUE TITLE
ActiveRecord wrapper for jobs

### ISSUE THREAD

**Issue by oniofchaos** [chanks/que#181]
Would there be any interest in accepting an ActiveRecord wrapper model for accessing Que jobs? Sometimes on production I need to investigate certain jobs/failing jobs and there's a few queries I run frequently

Count of jobs with errors:
`ActiveRecord::Base.connection.execute('select count(*) from que_jobs where error_count > 0').first`
could be something like 
`Que::Job.failed_jobs.count`

List of jobs of a certain type
`ActiveRecord::Base.connection.execute("select * from que_jobs where args->0->>'job_class' = 'SomeJob'")`
could be something like
`Que::Job.job_class('SomeJob')`

Thoughts?

**Comment by chanks** [comment]
Have you looked at the doc on inspecting the queue? You should be able to create your own ActiveRecord model for jobs pretty simply, and then use it to query however you like: https://github.com/chanks/que/blob/master/docs/inspecting_the_queue.md

**Comment by oniofchaos** [comment]
Neat!

Would you be interested in a PR that either makes that ActiveRecord model or adds additional methods to the [Que](https://github.com/chanks/que/blob/master/lib/que.rb) class for easier access? 
Example: `Que.job_count(queue: 'que_jobs')` vs `Que.execute("select count(*) from que_jobs")`

**Comment by chanks** [comment]
I don't have any objection to adding new introspection methods - there's already `Que.job_stats` which does basically what your suggestion does, for example. We could always add more if they seem useful enough.

Creating the ActiveRecord model (or Sequel model, or the model for whatever ORM the gem is being used with) is something I've thought about in the past, but it would probably make support for different versions of those ORMs more tricky than it is even now.

Also, the other attraction of just adding methods like `Que.job_stats` is that they can just invoke SQL directly and thus be adapter-independent. That method works even if you're using Que with a plain old PG connection that you made yourself.

**Comment by chanks** [comment]
Closing old issues - this feature exists in master now! Check out the 1.0 beta.
