### ISSUE TITLE
Is this a good config for Heroku?

### ISSUE THREAD

**Issue by 9mm** [chanks/que#183]
Hey there. I just switched from DelayedJob and after looking everything over a bunch I want to make sure I'm doing all this right:

Here are my goals:

1. Heroku `Procfile` has `web`, `clock`, and `worker` process types.
2. My `web` processes (which don't run any jobs, i.e. I don't use que's `:async` mode) is determined by `RAILS_MAX_THREADS`, (usually set to 5)
3. My clock and worker processes are intended to be a single thread. The idea here was that I would just scale more heroku dynos if I need more throughput. This app is dealing with finance, and all the 'meat' of the app happens in the jobs, so I'd rather err on the side of safety using a single thread and just scaling up many dynos if needed. My ability to determine thread safe gems is not 10/10

Here is my code:

**Procfile**

The overriding of `RAILS_MAX_THREADS` is to make sure worker/clock processes are set to a single worker, single pool connection in database (see `database.yml` below)

That way I can set `RAILS_MAX_THREADS` to `5` in the Heroku ENV variable settings area.

```
web: bundle exec puma -C config/puma.rb
clock: RAILS_MAX_THREADS=1 bundle exec clockwork config/clock.rb
worker: RAILS_MAX_THREADS=1 que ./config/environment.rb
```

**config/initializers/que.rb**

Notice worker count is based on `RAILS_MAX_THREADS`

```
Que.mode = :off
Que.worker_count = (ENV['RAILS_MAX_THREADS'] || 1).to_i
Que.wake_interval = 1.0
Que.logger = Logger.new(STDOUT)
```

**database.yml**

Notice the pool size is also based on `RAILS_MAX_THREADS`

```
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['RAILS_MAX_THREADS'] || 1 %>

...
```

Several questions:

1. Does the above config look acceptable for my goals? Que is a bit more complicated than DJ and I want to make sure my setup is good before deploying. The jobs are very important in my app :|
2. Do I still get the performance improvement over DJ even if I'm using a single thread (with multiple workers)?
3. What's the best way to listen for Heroku `SIGTERM` (and 10 seconds before `SIGKILL`), if my job is long running? Some of my jobs last 4 hours. This is how I solved it with DJ. Will this work with Que?

```
class WithdrawPaymentsJob

  def perform
    begin
      term_now = false
      old_term_handler = trap('TERM') { term_now = true; old_term_handler.call }

      loop do

        puts 'doing long running job'
        sleep 1

        if term_now
          raise 'Gracefully terminating job early...'
        end
      end

    ensure
      trap('TERM', old_term_handler)
    end
  end

end
```

**Comment by chanks** [comment]
A few things:

1. You shouldn't need to set `Que.mode = :off` if you're on a recent
version of the Gem, it'll default to off unless you're using the Que
executable.
2. The signal handling technique you're using is... a bit confusing? It
seems a lot simpler to just set a single term handler (in an initializer,
probably) that sets a global variable (`$app_shutting_down` or something)
and have the job(s) check for it. Continually swapping out the signal
handler feels like it's asking for trouble to me :-/
3. If you need more help, can you bring this up on the que-talk mailing
list? There's a link in the README. I'd like to keep the issue tracker to
just bugs, rather than general discussion.

Thanks!

**Comment by 9mm** [comment]
Ooops sorry will do.

RE: the SIGTERM thing, I got that answer from this SO thread: http://stackoverflow.com/questions/10438100/long-running-delayed-job-jobs-stay-locked-after-a-restart-on-heroku

How might I do it alternatively? (I'll re-ask this in the mailing list so you dont have to reply here)
