### ISSUE TITLE
Que : does it have perform_all? 

### ISSUE THREAD

**Issue by chrishough** [chanks/que#185]
When you are testing various jobs in Rspec is there something that can execute the jobs inside the queue similar to `ResqueSpec.perform_all(queue_name)`?   We have found the `rspec-que`library but it appears to be missing this functionality too. 

Thoughts?

**References**
https://github.com/leshill/resque_spec
https://github.com/gocardless/rspec-que

**Comment by chanks** [comment]
Going through old issues. There's not a `perform_all`-type method, the general testing strategy is to let jobs be persisted to the DB and then assert on their presence in tests. You can optionally also set jobs to run as they are queued - this is `Que.mode = :sync` in 0.x and `Que.run_synchronously = true` in 1.0.
