### ISSUE TITLE
[docs] Create failed_jobs without PK

### ISSUE THREAD

**Issue by aravindc26** [chanks/que#187]
In the doc https://github.com/chanks/que/blob/master/docs/customizing_que.md,  it has been mentioned to create fail_jobs table with the following statment

```
CREATE TABLE failed_jobs AS SELECT * FROM que_jobs LIMIT 0
```

But this creates a table without a primary key, was that intentional ?

**Comment by chanks** [comment]
It's just a quick one-liner example to create a table, the comment on the next line suggests doing a proper create table. What constraints and indexes you want on that table depends on how you're going to be querying it.
