### ISSUE TITLE
Triggering workers through Capistrano 

### ISSUE THREAD

**Issue by jeffling** [chanks/que#188]
Hi,

I'm trying to run something like `bundle exec que -l warn -q default ./config/environment.rb` through capistrano.

I'm finding it really hard to figure out how to gracefully start workers as a separate process with each deploy, and I want to avoid the :async option for various reasons. 

Is there a default way to do this? I know sidekiq has a capistrano-sidekiq gem, but looking into that isn't too helpful because they have tools like sidekiqctl. 

I wrote a simple script that initiates RVM and runs the task. Then in my capistrano task I have something like this:

`execute "nohup #{File.join(release_path, 'scripts', 'start_que.sh')} >> #{File.join(shared_path, 'log', 'que.log')} < /dev/null 2>&1 &"`

This doesn't output anything to the logs.

I then switched to this (removed ampersand) to see wtf was going on:\
 
`execute "nohup #{File.join(release_path, 'scripts', 'start_que.sh')} >> #{File.join(shared_path, 'log', 'que.log')} < /dev/null 2>&1 &"

Process executed fine, but even with `nohup`, the sighup terminated the process.

Anyways, I didn't mean to dump my SSHKIT specific issues here. I just wanted to know how other people were starting workers, perhaps using capistrano.

**Comment by jeffling** [comment]
For my specific case, it worked with

`execute "nohup bash -l -c 'bundle exec que -l warn -q default ./config/environment.rb >> /var/www/thisopenspace/shared/log/que.log 2>&1 &' > /dev/null 2>&1"` 

which makes sense but is crazy. I'd love to see what other people are doing for their deployments :)

**Comment by manfe** [comment]
@jeffling did you found any other way to do that?
