### ISSUE TITLE
Q: Stopping all workers

### ISSUE THREAD

**Issue by jsuchal** [chanks/que#193]
Hi there, 

is there a call to stop all workers? I've found `wake_all!` and looking for `stop_all!` i would like to stop work before deploying new application version. Our workers are running in separate containers / machines so it would be a nice feature to stop them from the main web app / admin.

**Comment by chanks** [comment]
Setting `Que.worker_count = 0` will have the workers all finish their current jobs and stop accepting new ones. It only works for workers in that Ruby process, so you can't call it across machines or anything.

The next major version uses Postgres' pub-sub to communicate with worker pools, so it'd be a nice feature to allow shutting workers down remotely. I added that to my list of features to investigate.
