### ISSUE TITLE
Fresh install fails

### ISSUE THREAD

**Issue by 9mm** [chanks/que#194]
I believe because of something introduced in Rails 5.1

```
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class AddQue < ActiveRecord::Migration[4.2]
```

**Comment by chanks** [comment]
Hmm, thanks, I'll look into it. I guess the migration syntax changed in 5.1?

**Comment by sbusso** [comment]
migrations are versioned since 5.0 to keep track of API changes, it needs to specify the version this migration is intended for:

```ruby
class AddQue < ActiveRecord::Migration[4.2]
```
