### ISSUE TITLE
Que Scheduler

### ISSUE THREAD

**Issue by hlascelles** [chanks/que#198]
We're finishing our migration off Resque to Que. A major hurdle is a replacement for [resque-scheduler](https://github.com/resque/resque-scheduler). We're considering a fork of resque-scheduler that changes the key line that schedules a job.

What are people using for scheduling que jobs? We'd like a multi-host aware system to prevent duplicate schedules (resque-scheduler uses a lock on a Redis key, which works great).

**Comment by joevandyk** [comment]
You can schedule que jobs in the future pretty easily by setting the run_at field to something in the future. 

Did you mean recurring jobs specifically?

**Comment by hlascelles** [comment]
That's it, cron'ing jobs.

**Comment by chanks** [comment]
You can pretty easily create jobs that repeat themselves on whatever cadence you like, see the section on it in the docs: https://github.com/chanks/que/blob/master/docs/customizing_que.md#recurring-jobs

**Comment by hlascelles** [comment]
I've taken your idea and run with it. I've created [que-scheduler](https://github.com/hlascelles/que-scheduler). It's a que job scheduler, configured with a yaml file containing job classes and their crons. 

It can handle an arbitrary number, with args. The file format is a superset of resque-scheduler's, so the migration should be easy (once the jobs have been migrated).

Let me know what you think.

**Comment by chanks** [comment]
Cool! Hope people find it helpful!
