### ISSUE TITLE
Executable raises NameError: uninitialized constant Que

### ISSUE THREAD

**Issue by NARKOZ** [chanks/que#202]
I'm trying to run jobs via [executable](https://github.com/chanks/que/blob/master/docs/managing_workers.md#working-jobs-via-executable), but it throws the error:

```
$ bundle exec que config/environment.rb &
[1] 27664
$ Could not load file 'config/environment.rb'
bundler: failed to load command: que (/var/www/app/shared/bundle/ruby/2.4.0/bin/que)
NameError: uninitialized constant Que
Did you mean?  Queue
  /var/www/app/shared/bundle/ruby/2.4.0/gems/que-0.14.2/bin/que:60:in `<top (required)>'
  /var/www/app/shared/bundle/ruby/2.4.0/bin/que:23:in `load'
  /var/www/app/shared/bundle/ruby/2.4.0/bin/que:23:in `<top (required)>'

[1]+  Exit 1                  bundle exec que config/environment.rb
```

**Comment by NARKOZ** [comment]
This is because que isn't required in https://github.com/chanks/que/blob/master/bin/que

**Comment by chanks** [comment]
Looks like `config/environment.rb` couldn't be found - ideally it would use Bundler to require Que (and everything else) for you. Is there a different file you need to require to boot your app?

**Comment by NARKOZ** [comment]
I've tried both with relative and absolute paths. The same error persists. `bundle exec rake que:work` works though.

>Is there a different file you need to require to boot your app?

No.

**Comment by chanks** [comment]
You tried `que ./config/environment.rb`? I think that's what worked for me back when I was implementing this (that's what the hint text in that file suggests, at least). If that doesn't work, maybe something is weird with your load path? That's a corner of Ruby that I don't know a ton about, unfortunately.

Adding a `require 'que'` to that file isn't going to help anything if your app isn't getting loaded - there won't be any job classes to run anyway.

**Comment by NARKOZ** [comment]
>You tried que ./config/environment.rb?

Yes, it didn't work though. I've solved the problem by generating binstub (`bundle binstubs que`) and then running `bin/que ./config/environment.rb`.
