### ISSUE TITLE
Migrating to 1.0.0.beta

### ISSUE THREAD

**Issue by 9mm** [chanks/que#207]
Hey, thanks for your great work on Que 1.0.0 (beta, so far).

Just to make sure I get the migration properly, can I show you my 'before and after' settings and you can tell me if I got everything right?

### Case 1 - initializers/que.rb

**Before**

```
Que.mode = :off
Que.worker_count = 1
Que.wake_interval = 5.0
Que.disable_prepared_statements = true
Que.logger = Logger.new(STDOUT)

Que.log_formatter = proc do |data|
  # exclude :job_unavailable which creates lots of chatter
  JSON.dump(data) unless data[:event] == :job_unavailable
end

Que.error_notifier = proc do |error|
  Raven.capture { raise error }
end
```

**After**

```
Que.use_prepared_statements = false
Que.logger = Logger.new(STDOUT)

Que.log_formatter = proc do |data|
  # exclude :job_unavailable which creates lots of chatter
  JSON.dump(data) unless data[:event] == :job_unavailable
end

Que.error_notifier = proc do |error|
  Raven.capture { raise error }
end
```

### Case 2 - models/que_job.rb

**Before**

```
class QueJob < ActiveRecord::Base
end
```

**After**

```
require 'que/active_record/model'

class QueJob < Que::ActiveRecord::Model
end
```

### Case 3 - que command in Procfile

**Before**

    que ./config/environment.rb

**After**

I think this...

    que ./config/environment.rb --worker-count 1 --poll-interval 5 --connection-url=$DATABASE_URL 

I noticed you removed `worker_count` and `wake_interval` from the config settings (which leads me to believe these settings are no longer needed), yet they're still configurable via command line if you use `que -h`. I assume they were just 'moved' and functionality wasn't actually 'removed'

### Case 4 - enqueuing jobs

**Before**

    BatchSendEmailJob.enqueue

**After**

No change I believe

### Case 5 - gracefully ending jobs

**Before**

```
class SendInvoicesJob < Que::Job
  def run
    10_000.times do do
      raise 'Gracefully terminating job early...' if Que.worker_count.zero?
      sleep 10 # emulate doing work for a lot of jobs
    end
  end
end
```

**After**

So on Heroku, they restart dynos every 24 hours at random intervals. This is what I had before to gracefully give Que workers a chance to shut down the very second a SIGTERM is sent by Heroku. It seems however that I can no longer use this `Que.worker_count` strategy. What should I do instead?

### Case 6 - Asserting a SINGLE running job

I'm kind of at a loss for the best way to do this, and I'm open to suggestions. The current way (which I pasted below), sucks, and uses 1 worker per session and use advisory locks (I use 1 worker per session for other reasons as well, mainly because I'm not very good at writing thread-safe code and I don't trust myself :p)

Hypothetical example: Lets say I have a job which operates on multiple records that sends invoice emails, and say it calls `users = User.with_unsent_invoices`. From there it sends the emails, and then calls `users.update_attributes(last_invoice_sent: Time.now)`. Then lets say all this happens in a transaction. My question is... if 6 workers are doing this simultaneously then how do I prevent it so if the same job gets enqueued a second (or third) time while the first is running, it won't cause issues where I'm sending 2 invoices? I get that Sidekiq recommends adding 1 job per record for something like this, I don't like that at all because I have millions of records. I'd be spending more time adding/removing jobs than doing the actual work.

**Before**

```
class BatchSendEmailJob < Que::Job

  def run
    (destroy && return) unless obtained_lock?

    begin
      loop do
        # do work here
      end
    ensure
      release_lock
    end
  end

  private

  def obtained_lock?
    ActiveRecord::Base.connection.select_value('SELECT pg_try_advisory_lock(1);')
  end

  def release_lock
    ActiveRecord::Base.connection.select_value('SELECT pg_advisory_unlock(1);')
  end

end
```

**After**

I have one job which batch sends emails in large groups, and only 1 job can be running at once. This is how I did this before... will this still work?

### Misc Errors

* **SOLVED BELOW** - I get the error of `could not obtain a connection from the pool within 5.000 seconds (waited 5.005 seconds); all pooled connections were in use (ActiveRecord::ConnectionTimeoutError)` when running the `que ./config/environment.rb` command. Maybe I'm wrong but doesn't it just use a standard connection to Postgres?
* I get an error `RuntimeError: Circular dependency detected while autoloading constant BatchSendEmailJob`. What's weird about this error is that it seems to only happen if theres existing jobs in the database when I start `que`. If I enqueue them in realtime when it's running, no errors get triggered.

### Misc Questions

* How exactly does `destroy` work if my job doesn't use a transaction? I notice it mentions the possibility of a job running twice [here](https://github.com/chanks/que/blob/1.0/docs/job_helper_methods.md): "ensuring that it won't be worked a second time". I need to make certain jobs aren't run twice. I can't tell if this is just an awkward sentence, or does it mean by not explicitly calling `destroy` it might get run twice?
* Do you recommend still trying to piggyback on the Rails connection? If I do this method, it seems I will need to adjust `database.yml` pool size to be something like `(ENV['RAILS_MAX_THREADS'] || 5) + 1` which seems kind of ugly (the `+ 1` to account for Que). Optionally, I can just connect directly using `--connection-url`, except now I can't use `ActiveRecord::Base.connection.select_value` to send a `pg_try_advisory_lock` query.
* In my app, Rails/Puma use PGBouncer, and so my `database.yml` disables prepared statements. Can I still use prepared statements in Que, just as long as I do a direction `--connection-url` and also never use PGBouncer with Que?

### Closing

In case a lot of this is unclear, these are my goals:

- Allow Que to be fully asynchronous with 6 workers, and using prepared statements for performance (PGBouncer not needed as long as all 6 workers share the same connection). That doesn't use many connections anyway.
- Do some type of database/advisory lock across ALL workers/queues/sessions/transactions/whatever. I have some jobs that can only be be running once at a time. Not once per thread or session or what-have-you... just globally database wide.
- Allow Puma+Rails to be single-threaded (with `database.yml` pool size set to 1), and using PGBouncer for Puma (so prepared statements are disabled in `database.yml` and for my rails app)

**Comment by 9mm** [comment]
Ok, I think I found out the connection timeout issue from [these docs](https://github.com/chanks/que/blob/1.0/docs/command_line_interface.md). It's because I'm disabling prepared statements. I did this originally because I use PGBouncer for Puma, and it said I need to set `prepared_statements: false` in my `database.yml` when doing that.

I disabled prepared statements in Que, just to be safe, but I don't think I need to if I'm connecting directly using `--connection-url` and I don't plan to use PGBouncer with Que, right (only Puma)? I'd rather use prepared statements for the extra performance.

**Comment by 9mm** [comment]
I've actually been toying around with trying to solve **Case 6** above.

This demo job is behaving very weirdly. I'd be curious to know what's going on.

I'm using

    que ./config/environment.rb -w 6 --connection-url=postgres://username:@127.0.0.1/que_test

If I put the code below, and queue 2 jobs a second apart (essentially, shorter than the `sleep 10`), the output shows

    CHECKING...
    OBTAINED LOCK: JOB RUNNING

Notice there is no second `CHECKING...`

```
class BatchSendEmailJob < Que::Job

  self.priority = 10

  def run
    puts 'CHECKING...'
    if obtained_lock?
      puts('OBTAINED LOCK: JOB RUNNING')
      sleep 10
      destroy
    else
      puts('FAILED OBTAINED LOCK')
      destroy
    end
  end

  private

  def obtained_lock?
    ActiveRecord::Base.connection.select_value('SELECT pg_try_advisory_lock(1);')
  end

  def release_lock
    ActiveRecord::Base.connection.select_value('SELECT pg_advisory_unlock(1);')
  end
end
```

Moments later I get a pool timeout error

This leads me to believe maybe there is some configuration I have wrong where there's only a single worker. If However... I do this...

```
  def run
    puts 'STARTING...'
    sleep 10
    puts 'STOPPING...'
  end
```

... and queue a bunch of jobs, it works as expected

```
STARTING...
STARTING...
STARTING...
STARTING...
STARTING...
STARTING...
... 6 seconds later...
STOPPING...
STARTING...
STOPPING...
STARTING...
```

I'm confused how this lock is causing the pool to "hang"

**Comment by chanks** [comment]
Case 1, 2 and 4 look right.

Case 3: worker_count was removed as a config setting for other reasons because it didn't really make sense as a global setting anymore, and it's only meaningful when running via the command line. `wake_interval` is no longer a thing (The new `poll-interval` CLI option serves kind of the same purpose, but it's less meaningful now with LISTEN/NOTIFY).

Case 5: There's no API explicitly for that right now, but when running from the CLI, SIGINT and SIGTERM do set `$stop_que_executable` to true, although this is kind of sloppy (as I mention in the comments) and isn't really meant to be a public API. I think you could use it for now, though.

Case 6: There's a lot going on here. A few notes:
- You can use `Que.execute("SELECT 1")` or `Que.execute("SELECT $1", ["bound variable"])` to use Que's connection pool if you want to.
- If things are set up right with ActiveRecord, Que's connection pool should be ActiveRecord's connection pool, so I don't see why `ActiveRecord::Base.connection.select_value` wouldn't work. You may need to wrap things in a `ActiveRecord::Base.connection_pool.with_connection{}` block to ensure that everything in the block uses the same connection.
- It's a bad idea to do something long-running (like hitting an external mail service) inside of a transaction. As a general rule you should try to keep transactions as short as possible - that makes it easier for postgres to clean up old records on the fly without waiting for a full autovacuum.
- The loading problem, I assume that your job file isn't being loaded until Que tries to work the job, and then I guess the job file tries to load Que? I don't use Rails myself so I'm not sure.
- If you don't call `destroy` yourself Que will call it for you, so you don't strictly need to do it. The helper is available to you because you generally want to call it inside a transaction with whatever other changes you're making as a result of the job being worked.
- Yes, currently the only place that prepared statements are used is when polling jobs, so if you're passing a database url to the executable then you should be able to leave prepared statements on.
- You don't necessarily need any explicit locking around that job if only one of them is enqueued at a time. Suppose you do something like (pseudocode):

```
def run
  User.with_unsent_invoices.each do |user|
    user.send_email
    user.update last_invoice_sent: Time.now
  end

  # All invoices sent, let's end this job and wait a minute before trying again.
  transaction do
    destroy
    self.class.enqueue(run_at: 1.minute.from_now)
  end
end
```

Then you kick off one of these jobs manually and let it reenqueue itself in perpetuity.

**Comment by 9mm** [comment]
Awesome! Thanks so much, let me experiment with all this. Those answers make lots of sense.

One fast question, how would I access `$stop_que_executable`?

**Comment by chanks** [comment]
It's a global variable, you can just reference it as you would any local or instance variable. They aren't used often and are generally considered an antipattern, but I wasn't sure what would be a better option in that case.

**Comment by 9mm** [comment]
Ah OK, I totally forgot ruby had global variables.

I'll come back and do some more testing in an hour or two, but I just tried using `Que.execute`. This works how I kind of expected now (all 6 workers using the same PG session).

Maybe this is more of a database question but how can I ensure only one job runs across ALL workers, regardless if they're in same/different sessions.

How can I attain a 'global lock' for this? I used to use advisory locks (with Que worker set to 1), but because there are multiple workers in a session, it always returns 'true'.

Essentially I just have some jobs that are vital that only 1 are running at a time, across the entire database.

**Comment by 9mm** [comment]
PS I should mention, I can't with absolute certainty say that more than one of them won't be queued at once. It's possible something in the clock scheduler bugs out/gets hung up, and the side effects of doing these actions twice would be very bad (dual billing people etc).

**Comment by chanks** [comment]
Btw, I'm not sure why you'd be able to get the lock when you weren't able to otherwise before. The session that holds all the job locks is held in a special thread/connection by Que itself (that's where the connection-url param goes), Que.execute shouldn't be using that same connection. So I'm not sure why you're seeing the behavior you are.

**Comment by 9mm** [comment]
Good idea about re-enqueing itself. I'd have to think about what happens if it gets off-sync somehow and doesn't get to run hourly.

Regarding the lock issue, this is the code I have. Is this a Que issue perhaps or something I'm doing wrong?

```
que ./config/environment.rb --worker-count 6 --connection-url=$DATABASE_URL
```

Rails console:

```
BatchSendEmailJob.enqueue; BatchSendEmailJob.enqueue; BatchSendEmailJob.enqueue; BatchSendEmailJob.enqueue
```

Output

```
OBTAINED
OBTAINED
OBTAINED
OBTAINED
DONE
DONE
DONE
DONE
```

Job:

```
class BatchSendEmailJob < Que::Job

  self.priority = 10

  def run
    if obtained_lock?
      puts 'OBTAINED'
      sleep 5
      puts 'DONE'
    else
      puts 'FAILED'
    end
  end

  private

  def obtained_lock?
    Que.execute('SELECT pg_try_advisory_lock(1);')
  end

  def release_lock
    Que.execute('SELECT pg_advisory_unlock(1);')
  end

end
```

Either way, I need to mull this over. Thanks for your help

**Comment by chanks** [comment]
I suspect that if you step through it you’ll find that the execute call is
returning an array (of results) which is always truthy for the if-condition.

**Comment by 9mm** [comment]
OH! Good eye!! I forgot to examine the output of `Que.execute` and how it differed from `ActiveRecord::Base.connection.select_value`... that's amazing.

Sadly it still appears to be the same result. Unless I'm insanely missing something, it now properly returns true/false and still does the same thing

```
  def obtained_lock?
    Que.execute('SELECT pg_try_advisory_lock(1);').first[:pg_try_advisory_lock]
  end

  def release_lock
    Que.execute('SELECT pg_advisory_unlock(1);').first[:pg_advisory_unlock]
  end
```

**Comment by chanks** [comment]
Hmm, maybe synchronize the connection to make sure that each job isn’t
reusing the same connection? I’m on my phone right now so I can’t check but
I think it’s something like Que.pool.synchronize(). Or you can just use the
ActiveRecord connection checkout logic that was elsewhere in this issue
(Que will just call that internally anyway).

**Comment by 9mm** [comment]
Nice, that worked!! (this code below). So just so I understand what's going on, the reason this works now is because `Que.pool.checkout` is forcing it to use it's own connection, so 100% of the time this code will execute always in a fresh connection?

Thanks again for all your help. If you have any changes with the $global_variable I'd be curious to know. I'll leave this thread open because I might have one or two more questions, or I can also put my journey in upgrading in case anyone else runs across this.

```
    Que.pool.checkout do
      if obtained_lock?
        begin
          puts 'OBTAINED'
          sleep 1
          puts 'DONE'
        ensure
          release_lock
        end
      else
        puts 'FAILED'
      end
    end
```

**Comment by 9mm** [comment]
Does this also 'release' the lock properly in my code here? I notice when I use `heroku local` to test, it gets through 10 loops before I start getting `could not obtain a connection from the pool within 5.000 seconds` errors, and the worker dies.

```
    Que.pool.checkout do
      if obtained_lock?
        begin
          count = 0
          loop do
            puts '.' * count
            count += 1
            sleep 1
            if $stop_que_executable
              raise 'GRACEFULLY TERMINATING'
            end
          end
        ensure
          release_lock
        end
      else
        puts 'FAILED'
        destroy
      end
    end
  end
```

**Comment by chanks** [comment]
That should release the lock, though I guess I’d put the actual lock taking
inside the begin block so that an error after it’s taken doesn’t run the
risk of leaving the lock in place.

It sounds like you’re exhausting your connection pool, you may want to
increase its size if you’re sure you want to keep locking explicitly.

**Comment by 9mm** [comment]
Bugger. Well I suppose I'll keep working on it. I guess it's confusing because it seems to me this code (with the locks) makes it so that when it fails immediately (within like 10 milliseconds) it should re-release it, but in my example it's most definitely not releasing it. It just captures them until it blows up even though the job ends.

Oh well though, I will just add it to my list of stuff to keep trying to fix

**Comment by chanks** [comment]
Closing this, since it's gotten kind of old and it's not really clear that the remaining issue is related to the gem.
