### ISSUE TITLE
Active Mailer / Active Jobs

### ISSUE THREAD

**Issue by fameoflight** [chanks/que#218]
How do I make this work with Active Mailer / Active Jobs? I am using 1.0.0.beta

Basically, I am doing .deliver_later in emails but they never get sent to que even though  I have this in my initializer 

Rails.application.config.active_job.queue_adapter = :que

Just wondering if I am missing something silly here

**Comment by stas** [comment]
@fameoflight take a look at #207 

Please report if you have any issues with the suggested guide.

**Comment by chanks** [comment]
@fameoflight That's not a lot of information to go on. Can you verify that `deliver_later` is creating a record in the `que_jobs` table? Are you sure that the workers are running properly (are other jobs being worked)?

@stas Did you mean to link to another issue? That one seems unrelated.

**Comment by DannyBen** [comment]
I am also very interested to know. I am looking to replace or amend my ActiveJob + Cron scheduling and queue management with something more reliable and persistent.

**Comment by jjb** [comment]
this blog post: https://blog.supersetinc.com/2017/12/21/que-performant-background-processing-rails-fewer-moving-parts/

says you need

```ruby
config.action_mailer.deliver_later_queue_name = ''
```

@chanks is this expected?

**Comment by chanks** [comment]
The default queue name changed to `default` in 1.0, but it looks like ActionMailer uses a queue called `mailers` by default, so I guess you'll want to use `config.action_mailer.deliver_later_queue_name = 'default'`.

**Comment by jjb** [comment]
@chanks thanks for that info.

I'm curious, why has this not come up before? I imagine using que with rails and actionmailer is extremely common.

**Comment by fameoflight** [comment]
Just wondering has any one tested 

```deliver_later(wait_until: send_at)``` 

When I check count on QueJob it's still 0 so I might missing something here

**Comment by chanks** [comment]
@jjb I suppose that people were using guides like the linked article for 0.x, and nobody had tried using 1.0 with ActiveJob yet?

@fameoflight :+1:, glad it's working for you now. I updated the main README with the above information, so I'm closing this.

**Comment by FarazPatankar** [comment]
Regarding the update to the README, I am using `config.action_mailer.deliver_later_queue_name = ''` with version 1.0.0.beta3 and it works just fine. Should I be changing the queue name to default or is it okay as it is?

**Comment by chanks** [comment]
Have you checked the jobs table to see if the jobs are actually being persisted with an empty string as the queue name? Alternatively, have you set `Que.default_queue = ""` or something similar?

**Comment by FarazPatankar** [comment]
I am probably missing something super obvious but how do I see the jobs table? I've tried a bunch of stuff in my Rails console but the only command that works is `Que.job_stats` which is just an aggregation.

Also, I haven't done anything like setting the `default_queue` to an empty string and I don't know if it is relevant but I am only using Que for the ActionMailer emails. I haven't configured anything else yet. The code below is all I've done apart from installing the gem.
```
# Use sql schema format
config.active_record.schema_format = :sql

# Allow que to pick up ActionMailer jobs
config.active_job.queue_adapter = :que
config.action_mailer.deliver_later_queue_name = ''
```

**Comment by FarazPatankar** [comment]
Just got around to checking this. Looks like the jobs have the queue name as default and not as an empty string. I also double checked and made sure that I haven't set `Que.default_queue = ""` anywhere.

This shouldn't be the case, right? Any idea why this is happening? Should I just change my `deliver_later_queue_name` to default and go ahead with it?

**Comment by chanks** [comment]
Maybe? I suspect that 1.0 broke that feature in ActiveJob’s logic, though
I’m not immediately sure of how, I was pretty careful to try to maintain
compatibility. I can look at it when I have time.

In any case, yeah, that setting should be “default”, unless you really
wanted to run multiple queues for some reason.
