### ISSUE TITLE
Running with more than one worker causes Que process to crash

### ISSUE THREAD

**Issue by newmana** [chanks/que#222]
Running with:
$ que -w 2

~/.rvm/gems/ruby-2.4.4/gems/que-1.0.0.beta3/lib/que/connection.rb:65:in `async_exec': ERROR:  relation "public.que_jobs" does not exist (PG::UndefinedTable)
LINE 1: SELECT 1 AS one FROM public.que_jobs WHERE id = $1::bigint
                             ^
	from ~.rvm/gems/ruby-2.4.4/gems/que-1.0.0.beta3/lib/que/connection.rb:65:in `block in execute'
	from (eval):9:in `run_sql_middleware'
	from ~.rvm/gems/ruby-2.4.4/gems/que-1.0.0.beta3/lib/que/connection.rb:60:in `execute'
	from ~.rvm/gems/ruby-2.4.4/gems/que-1.0.0.beta3/lib/que/connection_pool.rb:57:in `block in execute'
	from ~.rvm/gems/ruby-2.4.4/gems/que-1.0.0.beta3/lib/que/connection_pool.rb:39:in `block in checkout'
	from ~.rvm/gems/ruby-2.4.4/gems/que-1.0.0.beta3/lib/que/active_record/connection.rb:13:in `block (2 levels) in checkout'
	from ~.rvm/gems/ruby-2.4.4/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
	from ~.rvm/gems/ruby-2.4.4/gems/que-1.0.0.beta3/lib/que/active_record/connection.rb:12:in `block in checkout'
	from ~.rvm/gems/ruby-2.4.4/gems/activesupport-5.1.4/lib/active_support/execution_wrapper.rb:85:in `wrap'
	from ~.rvm/gems/ruby-2.4.4/gems/que-1.0.0.beta3/lib/que/active_record/connection.rb:23:in `wrap_in_rails_executor'
	from ~.rvm/gems/ruby-2.4.4/gems/que-1.0.0.beta3/lib/que/active_record/connection.rb:11:in `checkout'
	from ~.rvm/gems/ruby-2.4.4/gems/que-1.0.0.beta3/lib/que/connection_pool.rb:18:in `checkout'
	from ~.rvm/gems/ruby-2.4.4/gems/que-1.0.0.beta3/lib/que/connection_pool.rb:57:in `execute'
	from ~.rvm/gems/ruby-2.4.4/gems/que-1.0.0.beta3/lib/que/worker.rb:65:in `work_loop'
	from ~.rvm/gems/ruby-2.4.4/gems/que-1.0.0.beta3/lib/que/worker.rb:46:in `block in initialize'

The table definitely exists and the error does not happen when there is one worker.

**Comment by chanks** [comment]
That's very odd. Are you using ActiveRecord to connect to more than one database, or something? If you do `Que.execute("SELECT current_database()")` do you get consistent results?

**Comment by newmana** [comment]
This may exactly be what the problem is. Thanks for the hint - I’ll let you know as soon as I can.

**Comment by indicatrix-developers** [comment]
Yes there appears to be a connection to another database going on. Thanks for this.

**Comment by chanks** [comment]
:+1:
