### ISSUE TITLE
Multiple processes?

### ISSUE THREAD

**Issue by jjb** [chanks/que#225]
Is there a way to run multiple processes? I'd like to take advantage of all the memory on a server. Right now with 6 threads, my Que process uses 1/4-1/3 of the memory on a 1x heroku dyno. I could keep cranking up the threads but there's always some, and sometimes a lot, of benefit in using processes instead of threads for concurrency, so one may as well take advantage of it if it's available.

If there's no official or recommended way to do this, I could make a shell script that simply invokes `que` N times.

What do you think?

Thanks for an amazing project!

**Comment by chanks** [comment]
Nope, there's not a solution to this out of the box. I think the shell script is your best bet.

**Comment by jjb** [comment]
here's something i've put together. not in production yet. any feedback is appreciated, thanks!

```ruby
cluster_size = ENV["WORKER_CONCURRENCY"].to_i

puts "starting Que cluster with #{cluster_size} workers"; STDOUT.flush

pids = []
cluster_size.to_i.times do |n|
  puts "Starting Que daemon #{n}"; STDOUT.flush
  pids << Process.spawn("que --worker-count $MAX_THREADS")
end

%w[INT TERM].each do |signal|
  trap(signal) do
    pids.each{|pid| Process.kill(signal, pid) }
  end
end

Process.waitall

puts "Que cluster has shut down"; STDOUT.flush
```

**Comment by jjb** [comment]
(big thanks to @jstorimer's awesome book https://www.jstorimer.com/products/working-with-unix-processes )

**Comment by chanks** [comment]
That looks good!

I'm going to close this, but if anything else comes up please report back, I'm sure someone will find it useful.

**Comment by jjb** [comment]
maybe after we have it in production i'll submit a PR with this in /bin? or if you aren't ready for that, maybe a doc article?

**Comment by chanks** [comment]
I think a doc article would make sense, yeah!

**Comment by jjb** [comment]
FYI I am currently dealing with this problem:

https://stackoverflow.com/questions/52545629/how-can-a-process-die-in-a-way-that-process-wait-wouldnt-notice
