### ISSUE TITLE
job record does not "use" que given

### ISSUE THREAD

**Issue by StevenXL** [chanks/que#230]
Hi folks,

I hate to use the GitHub Issues as tech support, but I do not know where else to turn for help on this. 

I am sending out emails in a background job. The emails are getting enqueued and saved to the `que_jobs` table, but the `queue` is missing. 

Given the output below in my logs, it looks like ActionMailer is set up correctly and attempting to add the job to the `default` que. The part I am particularly paying attention to is `to Que(default)`. (Maybe that should say `to Que('default')`?). 

```
ActiveJob] Enqueued ActionMailer::DeliveryJob (Job ID: 5662be32-6677-41a7-9cfb-a823ab0e6641) to Que(default) with arguments: "DeviseMailer", "confirmation_instructions", "deliver_now", #<GlobalID:0x00007f9e9a2d8aa8 @uri=#<URI::GID gid://tfs/User/290087>>, "5s1YTeQHbZeiAdWZfyNy", {}
```

However, in the database I end up with a record such as the one below, where I have `"queue_name":"default"` in the `args` field, but the `queue` field is `''`. 

```
priority    │ 100
run_at      │ 2018-09-22 15:36:02.626098-05
job_id      │ 711870
job_class   │ ActiveJob::QueueAdapters::QueAdapter::JobWrapper
args        │ [{"job_class":"ActionMailer::DeliveryJob","job_id":"5662be32-6677-41a7-9cfb-a823ab0e6641","provider_job_id":null,"queue_name":"default","priority":null,"arguments":["DeviseMailer","confirmation_instructions","deliver_now",{"_aj_globalid":"gid://tfs/User/290087"},"5s1YTeQHbZeiAdWZfyNy",{"_aj_symbol_keys":[]}],"executions":0,"locale":"en"}]
error_count │ 0
last_error  │ [NULL]
queue       │
```

I am using `que 0.14.3`, `rails 5.2.0`, and `Postgres 9.4.11`.

**Comment by chanks** [comment]
Sorry for the delay, I've been taking a bit of time away from coding due to health issues.

The ActiveJob integration isn't super well-specced in the 0.x releases, so I'm not sure what that issue is. It's much better specced in the 1.0 releases (master, and the current release is 1.0.0.beta3). I realize that the "beta" label doesn't sound stable, but I've had production applications running on 1.0.0.beta3 for months now without issue. It could easily be called an RC, though I wouldn't want to jump to a final release without some more people trying it out.

**Comment by StevenXL** [comment]
@chanks Thanks for the reply, and sorry to hear about your health issues.

I'm going to close this comment, but if anyone else runs into this issue, we monkey-patched the adapter like so:

```ruby
# ./config/initializers/que.rb

# The only change we've added is the `queue` option to `JobWrapper#enqueue`, which is what `Que` is expecting to receive as a queue name option
#
# https://github.com/rails/rails/blob/master/activejob/lib/active_job/queue_adapters/que_adapter.rb
#
module ActiveJob
  module QueueAdapters
    class QueAdapter
      def enqueue(job)
        que_job = JobWrapper.enqueue job.serialize, queue: job.queue_name, priority: job.priority
        job.provider_job_id = que_job.attrs["job_id"]
        que_job
      end

      def enqueue_at(job, timestamp)
        que_job = JobWrapper.enqueue job.serialize, queue: job.queue_name, priority: job.priority, run_at: Time.at(timestamp)
        job.provider_job_id = que_job.attrs["job_id"]
        que_job
      end
    end
  end
end
```
