### ISSUE TITLE
One particular job is never run

### ISSUE THREAD

**Issue by benhoskings** [chanks/que#234]
G'day, we've just upgraded our production que deployment 1.0-beta (it's been running very reliably on 0.14.x for some time). It's processing in the order of hundreds of thousands of jobs per day, and all working very smoothly with one exception: a single job has appeared in our queue that is ready, but is never run.

It occurred to me that the transactional nature of job running might mean that that the job is locked but has become stuck, and that `finished_at`, `executions`, etc might well not be visibly updated outside the transaction in that case. I've restarted the que processes to no avail.

Are there any docs around that provide some guidance on interrogating the state of a job? I can start digging into the details of the new 1.0 schema but any pointers would be much appreciated as there's a bit to it.

The job can be seen in `QueJob.ready` output as other jobs move through (around 5 per second):

```
never_run = {
  "priority"=>6,
  "run_at"=>Mon, 11 Mar 2019 10:00:57 AEDT +11:00,
  "id"=>21569457,
  "job_class"=>"ActiveJob::QueueAdapters::QueAdapter::JobWrapper",
  "error_count"=>0,
  "last_error_message"=>nil,
  "queue"=>"default",
  "last_error_backtrace"=>nil,
  "finished_at"=>nil,
  "expired_at"=>nil,
  "args"=>[{"job_id"=>"ff22nnnn-nnnn-nnnn-nnnn-nnnnnnnnfd98",
  "locale"=>"en",
  "priority"=>6,
  "arguments"=>[{"_aj_globalid"=>"gid://api/Transaction/171nnnn"}],
  "job_class"=>"SendNewTransactionNotificationJob",
  "executions"=>0,
  "queue_name"=>"",
  "provider_job_id"=>nil}],
  "data"=>{}
}
```

Here's another of the same type that was enqueued and immediately run successfully as I was investigating:

```
succeeded = {
  "priority"=>6,
  "run_at"=>Tue, 12 Mar 2019 12:52:10 AEDT +11:00,
  "id"=>21951825,
  "job_class"=>"ActiveJob::QueueAdapters::QueAdapter::JobWrapper",
  "error_count"=>0,
  "last_error_message"=>nil,
  "queue"=>"default",
  "last_error_backtrace"=>nil,
  "finished_at"=>nil,
  "expired_at"=>nil,
  "args"=>[{"job_id"=>"ba3annnn-nnnn-nnnn-nnnn-nnnnnnnnb78e",
  "locale"=>"en",
  "priority"=>6,
  "arguments"=>[{"_aj_globalid"=>"gid://api/Transaction/174nnnn"}],
  "job_class"=>"SendNewTransactionNotificationJob",
  "executions"=>0,
  "queue_name"=>"",
  "provider_job_id"=>nil}],
  "data"=>{}
}
```

**Comment by benhoskings** [comment]
One correction - I didn't look closely enough at the pods after I restarted our que containers. There was one que container that took some time to terminate, and when it eventually did the above job also disappeared from the ready scope (presumably it was picked up again and run).

It looks like it actually was in some kind of stuck state. The cause of that could well be specific to our app.

Could you give some advice on investigating this for next time on the 1.0 schema? It'd be great to be able to extract some more info on the current state of a running job, and kill its current run if necessary to put it back on the queue.

Cheers :)

**Comment by chanks** [comment]
Hmm! Well, glad that it worked out.

You can call `Que.job_states` to return the list of jobs that are currently locked, including the hostname and pid of the process that locked them, it sounds like that would have pointed you directly to your problem. You might want to consider a shorter timeout than thirty minutes, though, since Que relies on Postgres noticing that a connection has been lost to free the locks on the jobs it had (this was true before 1.0 as well). When I've run 1.0 in production it was on Heroku, where the time between SIGTERM and SIGKILL was ten seconds, I believe?

**Comment by benhoskings** [comment]
Oh, it would have indeed. Thanks. I had `Que.job_states` confused with `Que.job_stats` and so was thinking only that aggregate info was easily available.

The 30 min timeout is on the container itself, to make sure that a long-running job won't be killed if we deploy while it runs. We could probably ratchet it down though, you're right.

Thanks for the quick reply. I'll keep an eye on it and do some more digging if it happens again.

Cheers mate!
