### ISSUE TITLE
Recommend a periodic manual vacuum in the readme?

### ISSUE THREAD

**Issue by mikehale** [chanks/que#243]
We have been running que-0.14.3 for awhile on a very high churn database. Recently we nearly had an outage because other large tables in our database were being autovacuumed which caused all 3 of the autovacuum workers to be unavailable for over 90 minutes, which meant that the que_jobs table was not getting vacuumed, which lead to working jobs more slowly than they were being added. Since we had plenty of IOPS available, to fix this issue and keep it from possibly happening again (if we got unlucky with autovacuum timing) we decided to add a process that started a manual vacuum of our high churn tables (of which que_jobs is one) every 5 minutes. So far this has been working great for us, and keeps our lock times at a very predictable level. I guess my question is, do you think periodic manual vacuums are something that should be generally recommended, and maybe included in the readme, or one of the other docs?

**Comment by chanks** [comment]
Maybe? I don't think it's general enough to belong in the readme, and I also think that whenever your database gets busy enough that the vacuum settings become significant, you're probably at the point where you want a Postgres expert to be managing it, and they'd already know how to handle this sort of thing. But it couldn't hurt to throw it in the docs somewhere.

**Comment by joevandyk** [comment]
I’ve also had to manually vacuum the jobs table regularly.

**Comment by mikehale** [comment]
I'm not a postgres expert by any stretch, just a developer and operator. It would be nice to have a dedicated postgres expert, but we still aren't in a position to have a person for that, and I imagine a lot of others are in the same boat. We've been running que in production since 2015, and only now realized that not relying on autovacuum to hopefully be available when we need it to keep dead tuples from growing without bound is a good idea. I thought it might be a good thing to call out so others can learn from our experience.

I haven't looked into que 1x too deeply, do you think the same advice will apply there?

**Comment by chanks** [comment]
I'm sure it will. I'd happily merge a PR adding this to the docs somewhere.

**Comment by chanks** [comment]
Closed by #244
