### ISSUE TITLE
rails/active job: Time casting fails

### ISSUE THREAD

**Issue by siegy22** [chanks/que#247]
Using rails `6.0.0.rc1` and pg `1.1.4`:

- `rails new foo && cd foo`
- (Add que to Gemfile, set `active_job.queue_adapter = :que` generate migration, migrate database)
- `rails g job example`
- `rails runner ExampleJob`

Resulting in:
```
Loading development environment (Rails 6.0.0.rc1)
irb(main):001:0> ExampleJob.perform_later
Enqueued ExampleJob (Job ID: 96741bc2-47a8-4efc-b768-bfab1e4395e5) to Que(default)
Traceback (most recent call last):
        1: from (irb):1
TypeError (no implicit conversion of Time into String)
```

**Comment by siegy22** [comment]
My assumption is that `pg` (since whatever version) automatically does the casting.

The following patch fixes this.

```patch
@@ -152,7 +152,11 @@ module Que
       },
 
       # Timestamp with time zone
-      1184 => Time.method(:parse),
+      1184 => -> (value) {
+        return value if value.is_a?(Time)
+
+        Time.parse(value)
+      },
     }
 
     # JSON, JSONB

```

**Comment by chanks** [comment]
Fixed in master.

**Comment by 9mm** [comment]
Is it possible to also fix this on 0.x branch? We use this in production and 1.0 wasnt stable enough, but it looks like it was only fixed on 1.0 beta

**Comment by danielpclark** [comment]
For those using the later versions of the `0.x` versions with Rails you can create a file `config/initializers/que.rb` and place the following in it.

```ruby
Que::Adapters::Base::CAST_PROCS[1184] = lambda do |value|
  case value
  when Time then value
  when String then Time.parse(value)
  else raise "Unexpected time class: #{value.class} (#{value.inspect})"
  end
end
```

This will patch the issue when upgrading to Rails 6.

**Comment by newbenji** [comment]
> Is it possible to also fix this on 0.x branch? We use this in production and 1.0 wasnt stable enough, but it looks like it was only fixed on 1.0 beta

Anything about 1.0 is ready?
and what issue did you see with 1.0...

**Comment by siegy22** [comment]
@newbenji Check the 1.0 milestone: https://github.com/que-rb/que/milestone/1

**Comment by LukeClancy** [comment]
This breaks que-web as well by the way, and the fix doesn't work for it
![Screenshot from 2020-12-23 17-55-58](https://user-images.githubusercontent.com/15352748/103050070-38edc300-4548-11eb-8477-e3986a74841f.png)
