### ISSUE TITLE
config.que.mode = :async in environments triggers intermittent ActiveRecord::ConnectionNotEstablished

### ISSUE THREAD

**Issue by tpitale** [chanks/que#73]
This appears to be a similar sort of race condition to #47. It seems the `wrangler` gets called when setting the mode, and because environments aren't in after_initialize (obviously) like how the railtie sets the mode, we get errors (but not always).

I don't think this needs a code fix, but a mention in the readme or docs might be helpful. Or at least someone can search issues and find this.

Thanks for this great gem!

**Comment by chanks** [comment]
Thank you for the report! I'm not sure what the ideal fix for this is right
now, but I'll be working on Que this weekend, so I'll look into it.

**Comment by chanks** [comment]
I figured that configuring Que in Rails' environment files is probably a bad idea because of this issue, so I just removed all mention of configuring things that way from the documentation. I think from now on this kind of setup should just be done in an initializer.
