### ISSUE TITLE
rails server log spam

### ISSUE THREAD

**Issue by louisshepherd** [chanks/que#78]
Hello, I just discovered this Project and I've started to integrate it into our app. I really like it's simplicity in setting up a new job, but I have one issue where I can't find any help on.

When I run 'rails server' it outputs every 5 seconds:

```javascript
{"lib":"que","hostname":"louis.speedport.ip","pid":42723,"thread":2240071600,"event":"job_unavailable"}
```

However, at this point I haven't actually scheduled any Jobs and the queries: 

```ruby
Que.execute( "select * from que_jobs" )
Que.worker_states
Que.job_stats
```
return an empty Array.

When I do run a job it gets scheduled and executed correctly, but the constant spamming is somewhat annoying.

Our App runs currently on Rails 4.1.4 and uses Postgres version 9.3.5

Any help / hint to solve this would be appreciated.

**Comment by chanks** [comment]
That logging is from the poll query, which most people find helpful. If you don't want it you can restrict it using the log formatter. See the last example in the [logging doc](https://github.com/chanks/que/blob/master/docs/logging.md).

**Comment by louisshepherd** [comment]
Ah, got it. Thank you for the quick response

**Comment by chanks** [comment]
No problem!
