### ISSUE TITLE
Instructions for setting up with rails not complete?

### ISSUE THREAD

**Issue by joevandyk** [chanks/que#80]
Running `rails generate que:install` just installs the migration, right? 

Isn't there something that needs to do `Que.connection = ActiveRecord` in a rails app that uses que?

**Comment by chanks** [comment]
The railtie does that automatically if ActiveRecord is defined.

**Comment by joevandyk** [comment]
Doesn't `Que.mode = :async` need to be set somewhere?

**Comment by chanks** [comment]
The railtie does that too :smile: 

I actually have a half-finished gem called que-rails that basically is the extracted railtie, but with specs that make sure that the rake task to create the migration works, and the worker pool boots properly in server mode, and all that. Basically those Rails integration things that aren't specced. Another thing I just haven't had the time to finish. If anyone wants to take it over I'd be happy to push it - I dislike having the Rails-specific stuff in the gem proper.

**Comment by joevandyk** [comment]
Ah, found the problem. I'm using rails-api, and rails-api doesn't define `Rails::Server`.

Not sure if the railtie should use a different constant or method to figure out if it can set `Que.mode = :async`?
