### ISSUE TITLE
Postgres 9.5devel - SKIP LOCKED

### ISSUE THREAD

**Issue by xpepermint** [chanks/que#87]
I would like to share info at [Postgres 9.5devel will support SELECT ... FOR UPDATE SKIP LOCKED](http://www.depesz.com/2014/10/10/waiting-for-9-5-implement-skip-locked-for-row-level-locks/). This will be great and we can optimize the code when it is released.

**Comment by marshall-lee** [comment]
Not everyone has a possibility to upgrade PostgreSQL to desired version :cry: Implement different behavior depending on version? It is also applies to #84 — we cannot rely on jsonb since it's only for >= 9.4

**Comment by xpepermint** [comment]
Well... we should add an `if` statement :).

**Comment by marshall-lee** [comment]
Hmm... Am I sure that it's useless since Que does job locking using advisory locks, not by `SELECT ... FOR UPDATE`?

I think, it can be useful for [queue_classic](https://github.com/QueueClassic/queue_classic) but not for Que.

**Comment by joevandyk** [comment]
I think the point is that you could avoid the complexity of advisory locks.
Might be worth looking at if it speeds things up.

You'd have to have two versions of the locking code though, until 9.4 and
earlier aren't supported anymore, probably 8 years out.

**Comment by chanks** [comment]
Yeah, I've read about it. One of the advantages of using advisory locks is that they're more robust in terms of failure recovery - if a process goes down, Postgres cleans up the locks for us and they can be picked up immediately by other workers, and you don't have the complexity and uncertainty of locked_at/locked_by columns. So I don't see us giving up advisory locks entirely anytime soon. It'd be very useful for DelayedJob and QueueClassic, though.

It's possible that we might be able to somehow use SKIP LOCKED to speed up the job lock query, though, to handle contention by multiple workers during locking, but I doubt it'd result in nearly the speed boost for Que as it would for DelayedJob or QueueClassic.
