### ISSUE TITLE
Job batching

### ISSUE THREAD

**Issue by Sinjo** [chanks/que#91]
I've been thinking this one through quite a bit, trying to work out if it's something that fits in with Que.

There are some jobs which get way more efficient if they're processed in batches. The two which immediately come to mind are sending webhooks, and syncing data changes to another store (e.g. a search cluster). The benefit in both cases is that you can make a single HTTP connection for a batch of enqueued jobs, rather than processing each one separately.

There's a bunch of implementation challenges that come to mind:

* How do job classes make themselves compatible with batch processing?
  * Presumably they need to register the maximum batch size they want to receive
  * Do they need a method like `run_batch` which gets passed an array of jobs to process?
* What does querying for jobs look like when you want to do batching?
  * To ensure batches are as large as possible, you'd need to include the job name as part of the locking query (otherwise you're just gonna get a mixture of jobs back and only be able to group a smaller number)
  * How badly would workers contend with each other on locking the same type of job?
  * How would you acquire a variable number of jobs at once? PL/pgSQL function?
  * Does batching fit better with `LISTEN`/`NOTIFY` (wait for n jobs to arrive or t seconds to pass, then create a batch)?
* What does acknowledgement look like?
  * Can you acknowledge only part of the batch as successful?
  * How does the job control the requeuing of the rest if so?

Very interested to hear your thoughts on this, and if it's something you've thought about before.

**Comment by chanks** [comment]
If the overhead of establishing connections is the concern, surely a connection pool would be a lot easier? I wrote a tiny one called [Pond](https://github.com/chanks/pond) that's been very reliable for me, and is thoroughly tested.

If you decide you need batch jobs, the [experimental](https://github.com/chanks/que/tree/experimental) branch contains a reworking of the gem to switch from single-job polling to a mixture of LISTEN/NOTIFY and batch polling. You may find some stuff in there useful. I wanted that branch to become 1.0, but I just haven't had the time to polish it off, and nobody's been complaining that Que is too slow, so it hasn't been a priority.

**Comment by Sinjo** [comment]
A connection pool is probably the right solution for the internal data syncing jobs. For webhooks, it's not really possible as they're being sent to a large number of third parties who we can't keep open connections to.

I'll have a look at the experimental branch. Totally understand not finishing that work if it's targeted at improving Que's performance. That already seems fast enough that executing the `run` method of most jobs is going to be the slow part.

**Comment by chanks** [comment]
Going to close this to try to clean up the issue tracker. I don't have many thoughts on it because it's not a use case I've personally run into, but you've clearly put a lot of thought into it, so I recommend reposting to the que-talk google group: https://groups.google.com/forum/#!forum/que-talk
