### ISSUE TITLE
Configure Que while in rake task

### ISSUE THREAD

**Issue by alex88** [chanks/que#95]
I'm trying to configure logging, while in a rails process it uses `Rails.logger` for logs, in the rake task it uses `STDOUT`. Is there a convention in where to configure Que while running in the rake task?

So I don't have to put everything in the workers

**Comment by chanks** [comment]
Hmm, yeah, it probably makes more sense to use the configured logger (which defaults to Rails.logger) in the rake task. I'll make that change, unless anyone has any objections?

**Comment by alex88** [comment]
Since Que doesn't load rails initializers, could makes sense to add a way to include a configuration script for the rake task?

**Comment by chanks** [comment]
The rake task has the :environment task as a dependency, so it should be running the initializers. It just manually sets the logging to go to STDOUT afterward. Are you sure it isn't running the initializers?

**Comment by alex88** [comment]
Ops you're right, it was foreman blocking stdout output. Anyway yes, the only thing I would need is to be able to configure the logger while in rake task

**Comment by chanks** [comment]
Would it work for you to use the Rails logger, or whatever Que is configured to use for logging in general? I don't want to have separate configuration options for working jobs in the server process and in a rake task unless it's really necessary.

**Comment by alex88** [comment]
For now yes, since I just want to be able to use loggly within the rake task :wink:

**Comment by chanks** [comment]
Alright, would you try the `rake-task-logger` branch and see if it works for you? I'm not set up to test it right now. I'll merge it into master before the next release if nobody complains about wanting the old behavior.

**Comment by alex88** [comment]
@chanks sorry for the delay, the branch works fine!

**Comment by chanks** [comment]
No problem, good to hear!

**Comment by chanks** [comment]
Merged and released in 0.10.0.
