### ISSUE TITLE
Large jobs?

### ISSUE THREAD

**Issue by joevandyk** [chanks/que#97]
More of a question than an issue (maybe time for que to have a mailing list or google group?)...

I need to use que to process a large uploaded file. Say the file is 1MB, 5MB, 10MB, 20MB, 50MB, or 100MB in size.

At what point would you stop storing the uploaded data into the que_jobs table and instead upload it to S3 and store the S3 URL in the que_job table?

**Comment by chanks** [comment]
Postgres will TOAST and compress the args hash if it gets big enough, so there's no hard limit on its size. In general, though, I don't think you want to be handling 1 MB+ strings in Ruby any more than you absolutely need to :smile:

Personally, I'd just always upload to S3 and call it a day, for flexibility and simplicity. If you want to have a cutoff, though, I'd go low, maybe somewhere around 100 K? It's probably worth experimenting with, though.

**Comment by joevandyk** [comment]
That's what I was thinking. That allows me to download the file and process it line by line, I don't think that would be possible when storing the data in the `que_jobs.args` column.
