### ISSUE TITLE
WARNING:  you don't own a lock of type ExclusiveLock

### ISSUE THREAD

**Issue by jemminger** [chanks/que#99]
I'm getting this error in development environment for some reason when `Que.mode = :async`  

Any ideas why?  I don't seem to remember ever seeing it before.

**Comment by chanks** [comment]
Hmm! Did you upgrade the gem or change anything else recently?

**Comment by jemminger** [comment]
Nothing's changed that I can tell.  I did notice now that I had two stuck jobs due to an exception with a missing association,  I cleared them out and the warning is gone now.  I'll close this and keep an eye on it.

**Comment by joevandyk** [comment]
What version of postgresql are you using?

**Comment by jemminger** [comment]
9.4.1.0, OSX 10.10.2

**Comment by chanks** [comment]
Wondering whether it's a good idea to keep many workers running in development for Rails apps, since I believe that code reloading isn't thread-safe...?
